;; -*- coding:utf-8-auto; -*-

;;
;; my theme
;;
(require 'custom)
(setq custom-theme-directory (concat my-dotfiles-dir "theme"))
(add-to-list 'load-path custom-theme-directory)
(setq custom-safe-themes t) ;; theme should be unsafe(?) though...

;; 폰트설정
;; 한글 폰트를 위한 설정. 아래 default-frame-alist에서 설정한 것을
;; 제외한 모든 다른 인코딩의 폰트는 fontset-default에 지정된 것이
;; 사용되는 것 같다.
;;
;;현재로서는 글꼴의 크기를 조정해서 폭을 맞추고 있어서, 한글과
;;영문간의 글꼴 크기 차이가 난다. font.c 의 코드를 보았지만, 아직은
;;spacing 이나 scalable 같은게 어떻게 동작하는지 이해를 못하고 있다.
(defvar my-default-font-name nil)
  (defvar my-default-font-size 90)
(cond
 (macp
  (setq my-default-font-name "Menlo" my-default-font-size 120))
 (win32p
  (setq my-default-font-name "Bitstream Vera Sans Mono" my-default-font-size 108))
 )
(defun my-setup-font-for-mbcs ()
  (interactive)
  (cond
   (macp
	(set-fontset-font "-*-*-*-*-*-*-*-*-*-*-*-*-fontset-default" 'korean-ksc5601 "NanumGothicCoding:weight=normal:spacing=m:scalable=true")
	(setq face-font-rescale-alist '(("NanumGothicCoding" . 1.21)))
	)
   (t
	(set-fontset-font "-*-*-*-*-*-*-*-*-*-*-*-*-fontset-default" 'korean-ksc5601 "나눔고딕코딩:weight=normal:spacing=m:scalable=true")
	(setq face-font-rescale-alist '(("나눔고딕코딩" . 1.23)))
	))
  (set-frame-font (concat my-default-font-name) t t)
  ;; (font . "나눔고딕코딩-12:normal:antialias=natural")
  ;; (font . "Monaco-11:normal:antialias=natural")
  ;; (font . "Anonymous Pro-11:normal:antialias=natural")
  ;; (font . "Andale Mono-10.0:bold:spacing=110:antialias=natural")
  ;; (font . "Monaco-12:normal:antialias=natural")
  ;; (font . "Ubuntu_Mono-14:normal:antialias=natural")
  ;; (font . "Menlo-13.5:normal:antialias=natural")
  )
;; 초기 테마
(load-theme 'my-tango-dark)
(defvar my-current-theme-is-dark t)

(setq my-theme-cycle-list '('my-zenburn 'my-solarized-dark 'my-solarized-light 'my-white))
(defvar my-default-dark-theme 'my-solarized-dark)
(defvar my-default-light-theme 'my-solarized-light)
(defun my-opposite-theme (curr-theme-name)
  (let ((curr-theme-split nil)
		(opposite-theme-split nil)
		)
	(if curr-theme-name
		(setq curr-theme-split (split-string curr-theme-name "-")))
	(if (> (length curr-theme-split) 2)
		(setq opposite-theme-split
			  (mapcar 
			   (lambda (e) 
				 (cond 
				  ((string= e "dark")
				   "light")
				  ((string= e "light")
				   "dark")
				  (t
				   e)))
			   curr-theme-split)))
	(c-concat-separated opposite-theme-split "-")
	)
  )
(defun my-toggle-theme ()
  (interactive)
  (let* ((current-theme (symbol-name (car custom-enabled-themes)))
		 (opposite-theme (my-opposite-theme current-theme)))
	(if (and (stringp opposite-theme)
			 (> (length opposite-theme) 0))
		(progn 
		  (mapcar 'disable-theme custom-enabled-themes)
		  (load-theme (intern opposite-theme) nil nil)
		  (message (format "loaded [%s] theme(opposite of [%s])" opposite-theme current-theme))
		  )
	  (call-interactively 'my-select-theme)
	  )
  )
)
(global-set-key (kbd "C-c t t") 'my-toggle-theme)

(defun my-select-theme (theme)
  (interactive
   (list (ido-completing-read "Select my theme: " (remove-if (lambda (s) (not (s-starts-with-p "my-" s))) (mapcar 'symbol-name (custom-available-themes))))))
  (mapcar 'disable-theme custom-enabled-themes)
  (load-theme (intern theme) nil nil)
  )
(global-set-key (kbd "C-c s t") 'my-select-theme)

;;
;;  from 'frame.c'
;;
;; static const struct frame_parm_table frame_parms[] =
;; {
;;   {"auto-raise",		&Qauto_raise},
;;   {"auto-lower",		&Qauto_lower},
;;   {"background-color",		0},
;;   {"border-color",		&Qborder_color},
;;   {"border-width",		&Qborder_width},
;;   {"cursor-color",		&Qcursor_color},
;;   {"cursor-type",		&Qcursor_type},
;;   {"font",			0},
;;   {"foreground-color",		0},
;;   {"icon-name",			&Qicon_name},
;;   {"icon-type",			&Qicon_type},
;;   {"internal-border-width",	&Qinternal_border_width},
;;   {"menu-bar-lines",		&Qmenu_bar_lines},
;;   {"mouse-color",		&Qmouse_color},
;;   {"name",			&Qname},
;;   {"scroll-bar-width",		&Qscroll_bar_width},
;;   {"title",			&Qtitle},
;;   {"unsplittable",		&Qunsplittable},
;;   {"vertical-scroll-bars",	&Qvertical_scroll_bars},
;;   {"visibility",		&Qvisibility},
;;   {"tool-bar-lines",		&Qtool_bar_lines},
;;   {"scroll-bar-foreground",	&Qscroll_bar_foreground},
;;   {"scroll-bar-background",	&Qscroll_bar_background},
;;   {"screen-gamma",		&Qscreen_gamma},
;;   {"line-spacing",		&Qline_spacing},
;;   {"left-fringe",		&Qleft_fringe},
;;   {"right-fringe",		&Qright_fringe},
;;   {"wait-for-wm",		&Qwait_for_wm},
;;   {"fullscreen",                &Qfullscreen},
;;   {"font-backend",		&Qfont_backend},
;;   {"alpha",			&Qalpha},
;;   {"sticky",			&Qsticky},
;;   {"tool-bar-position",		&Qtool_bar_position},
;; };

(progn
  (setq initial-frame-alist '())
  (setq frame-title-format (concat "Emacs " emacs-version " [%*] %f" ))
  (setq fringe-mode (quote (0 . 0))
		indicate-buffer-boundaries (quote left)
		indicate-empty-lines t
		)
  (setq
   default-frame-alist
   (cond
	((or win32p unixp)
	 `((menu-bar-lines . 0)
	   (tool-bar-lines . 0)
	   (alpha . (100 100))
	   (line-spacing . 0)
	   (font . ,(format "%s-%g" my-default-font-name (* 0.1 my-default-font-size)))
	   ;; (font . ,(format "%s" my-default-font-name))
	   ))
	(macp
	 `((menu-bar-lines . 0)
	   (tool-bar-lines . 0)
	   ;; (top . 0)
	   ;; (left . -1)
	   ;; (width . 115)
	   ;; (height . 71)
	   (font . ,(format "%s-%g" my-default-font-name (* 0.1 my-default-font-size)))
	   ))))
  (setq initial-frame-alist default-frame-alist)
  (modify-all-frames-parameters default-frame-alist)
  )

;; 잘못 만든 함수. 1) active frame의 2) alpha값만 바꾸어야 하는데. 초기
;; 프레임과 전체 frame parameter가 바뀐다. :(
;;
(defvar my-transparent-state-is-on t
  ""
  )
(defun my-toggle-transparent-state ()
  (interactive)
  (setq default-frame-alist
		(if my-transparent-state-is-on
		   '((alpha . (85 50)))
		  '((alpha . (100 100)))))
  (setq my-transparent-state-is-on (not my-transparent-state-is-on))
  (setq initial-frame-alist default-frame-alist)
  (modify-all-frames-parameters default-frame-alist)
  )
;; (global-set-key (kbd "C-c t") 'my-toggle-transparent-state)

;; 커스템 테마를 만든다음 실행할 함수.
(defun my-add-theme-faces ()
  (interactive)
  (custom-theme-add-face 'default)
  (custom-theme-add-face 'bold)
  (custom-theme-add-face 'bold-italic)
  (custom-theme-add-face 'fixed-pitch)
  (custom-theme-add-face 'italic)
  (custom-theme-add-face 'underline)
  (custom-theme-add-face 'variable-pitch)
  (custom-theme-add-face 'fringe)
  (custom-theme-add-face 'header-line)
  (custom-theme-add-face 'highlight)
  (custom-theme-add-face 'hover-highlight)
  (custom-theme-add-face 'match)
  (custom-theme-add-face 'menu)
  (custom-theme-add-face 'mouse)
  (custom-theme-add-face 'paren)
  (custom-theme-add-face 'trailing-whitespace)
  (custom-theme-add-face 'buffer-menu-buffer)
  (custom-theme-add-face 'border)
  (custom-theme-add-face 'button)
  (custom-theme-add-face 'cursor)
  (custom-theme-add-face 'escape-glyph-face)
  (custom-theme-add-face 'link)
  (custom-theme-add-face 'minibuffer-prompt)
  (custom-theme-add-face 'mode-line)
  (custom-theme-add-face 'mode-line-inactive)
  (custom-theme-add-face 'mode-line-buffer-id)
  (custom-theme-add-face 'mode-line-emphasis)
  (custom-theme-add-face 'mode-line-highlight)
  (custom-theme-add-face 'region)
  (custom-theme-add-face 'scroll-bar)
  (custom-theme-add-face 'secondary-selection)
  (custom-theme-add-face 'tool-bar)
  ;; 
  (custom-theme-add-face 'apt-utils-broken)
  (custom-theme-add-face 'apt-utils-description)
  (custom-theme-add-face 'apt-utils-field-contents)
  (custom-theme-add-face 'apt-utils-field-keyword)
  (custom-theme-add-face 'apt-utils-normal-package)
  (custom-theme-add-face 'apt-utils-summary)
  (custom-theme-add-face 'apt-utils-version)
  (custom-theme-add-face 'apt-utils-virtual-package)
  (custom-theme-add-face 'breakpoint-disabled-bitmap)
  (custom-theme-add-face 'breakpoint-enabled-bitmap)
  (custom-theme-add-face 'calendar-today)
  (custom-theme-add-face 'change-log-date)
  (custom-theme-add-face 'circe-highlight-nick-face)
  (custom-theme-add-face 'circe-my-message-face)
  (custom-theme-add-face 'circe-originator-face)
  (custom-theme-add-face 'circe-prompt-face)
  (custom-theme-add-face 'circe-server-face)
  (custom-theme-add-face 'comint-highlight-input)
  (custom-theme-add-face 'comint-highlight-prompt)
  (custom-theme-add-face 'compilation-info)
  (custom-theme-add-face 'compilation-warning)
  (custom-theme-add-face 'cscope-line-face)
  (custom-theme-add-face 'cua-rectangle)
  (custom-theme-add-face 'custom-button)
  (custom-theme-add-face 'custom-button-pressed)
  (custom-theme-add-face 'custom-changed)
  (custom-theme-add-face 'custom-comment)
  (custom-theme-add-face 'custom-comment-tag)
  (custom-theme-add-face 'custom-documentation)
  (custom-theme-add-face 'custom-group-tag)
  (custom-theme-add-face 'custom-group-tag-1)
  (custom-theme-add-face 'custom-invalid)
  (custom-theme-add-face 'custom-link)
  (custom-theme-add-face 'custom-modified)
  (custom-theme-add-face 'custom-rogue)
  (custom-theme-add-face 'custom-saved)
  (custom-theme-add-face 'custom-set)
  (custom-theme-add-face 'custom-state)
  (custom-theme-add-face 'custom-tag)
  (custom-theme-add-face 'custom-variable-button)
  (custom-theme-add-face 'custom-variable-tag)
  (custom-theme-add-face 'diary)
  (custom-theme-add-face 'dictionary-button)
  (custom-theme-add-face 'dictionary-reference)
  (custom-theme-add-face 'dictionary-word-entry)
  (custom-theme-add-face 'diff-added-face)
  (custom-theme-add-face 'diff-context-face)
  (custom-theme-add-face 'diff-file-header-face)
  (custom-theme-add-face 'diff-header-face)
  (custom-theme-add-face 'diff-hunk-header-face)
  (custom-theme-add-face 'diff-index-face)
  (custom-theme-add-face 'diff-refine-added)
  (custom-theme-add-face 'diff-refine-change-face)
  (custom-theme-add-face 'diff-removed-face)
  (custom-theme-add-face 'diredp-compressed-file-suffix)
  (custom-theme-add-face 'diredp-date-time)
  (custom-theme-add-face 'diredp-default)
  (custom-theme-add-face 'diredp-deletion)
  (custom-theme-add-face 'diredp-deletion-file-name)
  (custom-theme-add-face 'diredp-dir-heading)
  (custom-theme-add-face 'diredp-dir-priv)
  (custom-theme-add-face 'diredp-display-msg)
  (custom-theme-add-face 'diredp-exec-priv)
  (custom-theme-add-face 'diredp-executable-tag)
  (custom-theme-add-face 'diredp-file-name)
  (custom-theme-add-face 'diredp-file-suffix)
  (custom-theme-add-face 'diredp-flag-mark)
  (custom-theme-add-face 'diredp-flag-mark-line)
  (custom-theme-add-face 'diredp-ignored-file-name)
  (custom-theme-add-face 'diredp-link-priv)
  (custom-theme-add-face 'diredp-no-priv)
  (custom-theme-add-face 'diredp-number)
  (custom-theme-add-face 'diredp-other-priv)
  (custom-theme-add-face 'diredp-rare-priv)
  (custom-theme-add-face 'diredp-read-priv)
  (custom-theme-add-face 'diredp-symlink)
  (custom-theme-add-face 'diredp-write-priv)
  (custom-theme-add-face 'ediff-current-diff-A)
  (custom-theme-add-face 'ediff-current-diff-B)
  (custom-theme-add-face 'ediff-current-diff-C)
  (custom-theme-add-face 'ediff-old-diff-A)
  (custom-theme-add-face 'ediff-old-diff-B)
  (custom-theme-add-face 'ediff-old-diff-C)
  (custom-theme-add-face 'emms-pbi-current)
  (custom-theme-add-face 'emms-pbi-mark-marked)
  (custom-theme-add-face 'emms-pbi-song)
  (custom-theme-add-face 'erc-action-face)
  (custom-theme-add-face 'erc-bold-face)
  (custom-theme-add-face 'erc-current-nick-face)
  (custom-theme-add-face 'erc-dangerous-host-face)
  (custom-theme-add-face 'erc-default-face)
  (custom-theme-add-face 'erc-direct-msg-face)
  (custom-theme-add-face 'erc-error-face)
  (custom-theme-add-face 'erc-fool-face)
  (custom-theme-add-face 'erc-highlight-face)
  (custom-theme-add-face 'erc-input-face)
  (custom-theme-add-face 'erc-keyword-face)
  (custom-theme-add-face 'erc-my-nick-face)
  (custom-theme-add-face 'erc-nick-default-face)
  (custom-theme-add-face 'erc-nick-msg-face)
  (custom-theme-add-face 'erc-notice-face)
  (custom-theme-add-face 'erc-pal-face)
  (custom-theme-add-face 'erc-prompt-face)
  (custom-theme-add-face 'erc-timestamp-face)
  (custom-theme-add-face 'erc-underline-face)
  (custom-theme-add-face 'eshell-ls-archive)
  (custom-theme-add-face 'eshell-ls-backup)
  (custom-theme-add-face 'eshell-ls-clutter)
  (custom-theme-add-face 'eshell-ls-directory)
  (custom-theme-add-face 'eshell-ls-executable)
  (custom-theme-add-face 'eshell-ls-missing)
  (custom-theme-add-face 'eshell-ls-product)
  (custom-theme-add-face 'eshell-ls-special)
  (custom-theme-add-face 'eshell-ls-symlink)
  (custom-theme-add-face 'eshell-ls-unreadable)
  (custom-theme-add-face 'eshell-prompt)
  (custom-theme-add-face 'fancy-widget-button)
  (custom-theme-add-face 'fancy-widget-button-highlight)
  (custom-theme-add-face 'fancy-widget-button-pressed)
  (custom-theme-add-face 'fancy-widget-button-pressed-highlight)
  (custom-theme-add-face 'fancy-widget-documentation)
  (custom-theme-add-face 'fancy-widget-field)
  (custom-theme-add-face 'fancy-widget-inactive)
  (custom-theme-add-face 'fancy-widget-single-line-field)
  (custom-theme-add-face 'flyspell-duplicate)
  (custom-theme-add-face 'flyspell-incorrect)
  (custom-theme-add-face 'font-latex-bold)
  (custom-theme-add-face 'font-latex-sedate)
  (custom-theme-add-face 'font-latex-title-4)
  (custom-theme-add-face 'font-latex-warning)
  (custom-theme-add-face 'font-lock-builtin-face)
  (custom-theme-add-face 'font-lock-comment-delimiter-face)
  (custom-theme-add-face 'font-lock-comment-face)
  (custom-theme-add-face 'font-lock-constant-face)
  (custom-theme-add-face 'font-lock-doc-face)
  (custom-theme-add-face 'font-lock-doc-string-face)
  (custom-theme-add-face 'font-lock-function-name-face)
  (custom-theme-add-face 'font-lock-keyword-face)
  (custom-theme-add-face 'font-lock-negation-char-face)
  (custom-theme-add-face 'font-lock-operator-face)
  (custom-theme-add-face 'font-lock-preprocessor-face)
  (custom-theme-add-face 'font-lock-pseudo-keyword-face)
  (custom-theme-add-face 'font-lock-string-face)
  (custom-theme-add-face 'font-lock-type-face)
  (custom-theme-add-face 'font-lock-variable-name-face)
  (custom-theme-add-face 'font-lock-warning-face)
  (custom-theme-add-face 'gnus-cite-1-face)
  (custom-theme-add-face 'gnus-cite-10-face)
  (custom-theme-add-face 'gnus-cite-11-face)
  (custom-theme-add-face 'gnus-cite-2-face)
  (custom-theme-add-face 'gnus-cite-3-face)
  (custom-theme-add-face 'gnus-cite-4-face)
  (custom-theme-add-face 'gnus-cite-5-face)
  (custom-theme-add-face 'gnus-cite-6-face)
  (custom-theme-add-face 'gnus-cite-7-face)
  (custom-theme-add-face 'gnus-cite-8-face)
  (custom-theme-add-face 'gnus-cite-9-face)
  (custom-theme-add-face 'gnus-group-mail-1-empty-face)
  (custom-theme-add-face 'gnus-group-mail-1-face)
  (custom-theme-add-face 'gnus-group-mail-2-empty-face)
  (custom-theme-add-face 'gnus-group-mail-2-face)
  (custom-theme-add-face 'gnus-group-mail-3-empty-face)
  (custom-theme-add-face 'gnus-group-mail-3-face)
  (custom-theme-add-face 'gnus-group-mail-4-empty-face)
  (custom-theme-add-face 'gnus-group-mail-4-face)
  (custom-theme-add-face 'gnus-group-mail-5-empty-face)
  (custom-theme-add-face 'gnus-group-mail-5-face)
  (custom-theme-add-face 'gnus-group-mail-6-empty-face)
  (custom-theme-add-face 'gnus-group-mail-6-face)
  (custom-theme-add-face 'gnus-group-mail-low-empty-face)
  (custom-theme-add-face 'gnus-group-mail-low-face)
  (custom-theme-add-face 'gnus-group-news-1-empty-face)
  (custom-theme-add-face 'gnus-group-news-1-face)
  (custom-theme-add-face 'gnus-group-news-2-empty-face)
  (custom-theme-add-face 'gnus-group-news-2-face)
  (custom-theme-add-face 'gnus-group-news-3-empty-face)
  (custom-theme-add-face 'gnus-group-news-3-face)
  (custom-theme-add-face 'gnus-group-news-4-empty-face)
  (custom-theme-add-face 'gnus-group-news-4-face)
  (custom-theme-add-face 'gnus-group-news-5-empty-face)
  (custom-theme-add-face 'gnus-group-news-5-face)
  (custom-theme-add-face 'gnus-group-news-6-empty-face)
  (custom-theme-add-face 'gnus-group-news-6-face)
  (custom-theme-add-face 'gnus-group-news-low-empty-face)
  (custom-theme-add-face 'gnus-group-news-low-face)
  (custom-theme-add-face 'gnus-header-content-face)
  (custom-theme-add-face 'gnus-header-from-face)
  (custom-theme-add-face 'gnus-header-name-face)
  (custom-theme-add-face 'gnus-header-newsgroups-face)
  (custom-theme-add-face 'gnus-header-subject-face)
  (custom-theme-add-face 'gnus-signature-face)
  (custom-theme-add-face 'gnus-summary-cancelled-face)
  (custom-theme-add-face 'gnus-summary-high-ancient-face)
  (custom-theme-add-face 'gnus-summary-high-read-face)
  (custom-theme-add-face 'gnus-summary-high-ticked-face)
  (custom-theme-add-face 'gnus-summary-high-unread-face)
  (custom-theme-add-face 'gnus-summary-low-ancient-face)
  (custom-theme-add-face 'gnus-summary-low-read-face)
  (custom-theme-add-face 'gnus-summary-low-ticked-face)
  (custom-theme-add-face 'gnus-summary-low-unread-face)
  (custom-theme-add-face 'gnus-summary-normal-ancient-face)
  (custom-theme-add-face 'gnus-summary-normal-read-face)
  (custom-theme-add-face 'gnus-summary-normal-ticked-face)
  (custom-theme-add-face 'gnus-summary-normal-unread-face)
  (custom-theme-add-face 'gnus-summary-selected-face)
  (custom-theme-add-face 'gnus-x-face)
  (custom-theme-add-face 'helm-ff-directory)
  (custom-theme-add-face 'helm-ff-executable)
  (custom-theme-add-face 'helm-ff-file)
  (custom-theme-add-face 'helm-grep-file)
  (custom-theme-add-face 'helm-grep-match)
  (custom-theme-add-face 'helm-header)
  (custom-theme-add-face 'helm-match)
  (custom-theme-add-face 'helm-selection)
  (custom-theme-add-face 'helm-selection-line)
  (custom-theme-add-face 'helm-source-header)
  (custom-theme-add-face 'helm-visible-mark)
  (custom-theme-add-face 'help-argument-name)
  (custom-theme-add-face 'hi-blue)
  (custom-theme-add-face 'hi-green)
  (custom-theme-add-face 'hi-pink)
  (custom-theme-add-face 'hi-yellow)
  (custom-theme-add-face 'highlight-current-line)
  (custom-theme-add-face 'hl-line)
  (custom-theme-add-face 'holiday)
  (custom-theme-add-face 'ibuffer-deletion)
  (custom-theme-add-face 'ibuffer-help-buffer)
  (custom-theme-add-face 'ibuffer-marked)
  (custom-theme-add-face 'ibuffer-special-buffer)
  (custom-theme-add-face 'icompletep-choices)
  (custom-theme-add-face 'icompletep-determined)
  (custom-theme-add-face 'icompletep-keys)
  (custom-theme-add-face 'icompletep-nb-candidates)
  (custom-theme-add-face 'ido-first-match)
  (custom-theme-add-face 'ido-only-match)
  (custom-theme-add-face 'ido-subdir)
  (custom-theme-add-face 'imaxima-latex-error)
  (custom-theme-add-face 'info-header-node)
  (custom-theme-add-face 'info-header-xref)
  (custom-theme-add-face 'info-menu-5)
  (custom-theme-add-face 'info-menu-header)
  (custom-theme-add-face 'info-menu-star)
  (custom-theme-add-face 'info-node)
  (custom-theme-add-face 'info-title-4)
  (custom-theme-add-face 'info-xref)
  (custom-theme-add-face 'info-xref-visited)
  (custom-theme-add-face 'isearch)
  (custom-theme-add-face 'isearch-fail)
  (custom-theme-add-face 'jabber-chat-prompt-foreign)
  (custom-theme-add-face 'jabber-chat-prompt-local)
  (custom-theme-add-face 'jabber-rare-time-face)
  (custom-theme-add-face 'jabber-roster-user-away)
  (custom-theme-add-face 'jabber-roster-user-chatty)
  (custom-theme-add-face 'jabber-roster-user-dnd)
  (custom-theme-add-face 'jabber-roster-user-error)
  (custom-theme-add-face 'jabber-roster-user-offline)
  (custom-theme-add-face 'jabber-roster-user-online)
  (custom-theme-add-face 'jabber-roster-user-xa)
  (custom-theme-add-face 'jabber-title-large)
  (custom-theme-add-face 'jabber-title-medium)
  (custom-theme-add-face 'jabber-title-small)
  (custom-theme-add-face 'jde-java-font-lock-constant-face)
  (custom-theme-add-face 'jde-java-font-lock-doc-tag-face)
  (custom-theme-add-face 'jde-java-font-lock-link-face)
  (custom-theme-add-face 'jde-java-font-lock-modifier-face)
  (custom-theme-add-face 'jde-java-font-lock-number-face)
  (custom-theme-add-face 'jde-java-font-lock-operator-face)
  (custom-theme-add-face 'jde-java-font-lock-package-face)
  (custom-theme-add-face 'keywiz-command-face)
  (custom-theme-add-face 'keywiz-right-face)
  (custom-theme-add-face 'keywiz-wrong-face)
  (custom-theme-add-face 'lazy-highlight)
  (custom-theme-add-face 'magit-branch)
  (custom-theme-add-face 'magit-item-highlight)
  (custom-theme-add-face 'magit-section-title)
  (custom-theme-add-face 'makefile-shell)
  (custom-theme-add-face 'makefile-space)
  (custom-theme-add-face 'message-cited-text-face)
  (custom-theme-add-face 'message-header-cc-face)
  (custom-theme-add-face 'message-header-from-face)
  (custom-theme-add-face 'message-header-name-face)
  (custom-theme-add-face 'message-header-newsgroups-face)
  (custom-theme-add-face 'message-header-other-face)
  (custom-theme-add-face 'message-header-subject-face)
  (custom-theme-add-face 'message-header-to-face)
  (custom-theme-add-face 'message-header-xheader-face)
  (custom-theme-add-face 'message-mml-face)
  (custom-theme-add-face 'message-separator-face)
  (custom-theme-add-face 'minimap-active-region-background)
  (custom-theme-add-face 'mm/master-face)
  (custom-theme-add-face 'mm/mirror-face)
  (custom-theme-add-face 'org-agenda-clocking)
  (custom-theme-add-face 'org-agenda-date)
  (custom-theme-add-face 'org-agenda-date-today)
  (custom-theme-add-face 'org-agenda-date-weekend)
  (custom-theme-add-face 'org-agenda-structure)
  (custom-theme-add-face 'org-archived)
  (custom-theme-add-face 'org-checkbox)
  (custom-theme-add-face 'org-date)
  (custom-theme-add-face 'org-deadline-announce)
  (custom-theme-add-face 'org-document-title)
  (custom-theme-add-face 'org-done)
  (custom-theme-add-face 'org-formula)
  (custom-theme-add-face 'org-headline-done)
  (custom-theme-add-face 'org-hide)
  (custom-theme-add-face 'org-level-1)
  (custom-theme-add-face 'org-level-2)
  (custom-theme-add-face 'org-level-3)
  (custom-theme-add-face 'org-level-4)
  (custom-theme-add-face 'org-level-5)
  (custom-theme-add-face 'org-level-6)
  (custom-theme-add-face 'org-level-7)
  (custom-theme-add-face 'org-level-8)
  (custom-theme-add-face 'org-link)
  (custom-theme-add-face 'org-scheduled)
  (custom-theme-add-face 'org-scheduled-previously)
  (custom-theme-add-face 'org-scheduled-today)
  (custom-theme-add-face 'org-special-keyword)
  (custom-theme-add-face 'org-table)
  (custom-theme-add-face 'org-tag)
  (custom-theme-add-face 'org-time-grid)
  (custom-theme-add-face 'org-todo)
  (custom-theme-add-face 'org-upcoming-deadline)
  (custom-theme-add-face 'org-warning)
  (custom-theme-add-face 'outline-1)
  (custom-theme-add-face 'outline-2)
  (custom-theme-add-face 'outline-3)
  (custom-theme-add-face 'outline-4)
  (custom-theme-add-face 'outline-5)
  (custom-theme-add-face 'outline-6)
  (custom-theme-add-face 'outline-7)
  (custom-theme-add-face 'outline-8)
  (custom-theme-add-face 'rainbow-delimiters-depth-1-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-10-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-11-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-12-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-2-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-3-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-4-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-5-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-6-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-7-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-8-face)
  (custom-theme-add-face 'rainbow-delimiters-depth-9-face)
  (custom-theme-add-face 'rcirc-bright-nick)
  (custom-theme-add-face 'rcirc-dim-nick)
  (custom-theme-add-face 'rcirc-mode-line-nick)
  (custom-theme-add-face 'rcirc-my-nick)
  (custom-theme-add-face 'rcirc-nick-in-message)
  (custom-theme-add-face 'rcirc-other-nick)
  (custom-theme-add-face 'rcirc-prompt)
  (custom-theme-add-face 'rcirc-server)
  (custom-theme-add-face 'rcirc-server-prefix)
  (custom-theme-add-face 'rcirc-timestamp)
  (custom-theme-add-face 'rst-level-1-face)
  (custom-theme-add-face 'rst-level-2-face)
  (custom-theme-add-face 'rst-level-3-face)
  (custom-theme-add-face 'rst-level-4-face)
  (custom-theme-add-face 'setnu-line-number)
  (custom-theme-add-face 'show-paren-match)
  (custom-theme-add-face 'show-paren-mismatch)
  (custom-theme-add-face 'speedbar-button-face)
  (custom-theme-add-face 'speedbar-directory-face)
  (custom-theme-add-face 'speedbar-file-face)
  (custom-theme-add-face 'speedbar-highlight-face)
  (custom-theme-add-face 'speedbar-tag-face)
  (custom-theme-add-face 'strokes-char-face)
  (custom-theme-add-face 'todoo-item-assigned-header-face)
  (custom-theme-add-face 'todoo-item-header-face)
  (custom-theme-add-face 'todoo-sub-item-header-face)
  (custom-theme-add-face 'tuareg-font-lock-governing-face)
  (custom-theme-add-face 'tuareg-font-lock-interactive-error-face)
  (custom-theme-add-face 'tuareg-font-lock-interactive-output-face)
  (custom-theme-add-face 'tuareg-font-lock-operator-face)
  (custom-theme-add-face 'twittering-uri-face)
  (custom-theme-add-face 'twittering-username-face)
  (custom-theme-add-face 'w3m-anchor-face)
  (custom-theme-add-face 'w3m-arrived-anchor-face)
  (custom-theme-add-face 'w3m-form-button-face)
  (custom-theme-add-face 'w3m-form-button-mouse-face)
  (custom-theme-add-face 'w3m-form-button-pressed-face)
  (custom-theme-add-face 'w3m-form-face)
  (custom-theme-add-face 'w3m-image-face)
  (custom-theme-add-face 'w3m-tab-background-face)
  (custom-theme-add-face 'w3m-tab-selected-face)
  (custom-theme-add-face 'w3m-tab-selected-retrieving-face)
  (custom-theme-add-face 'w3m-tab-unselected-face)
  (custom-theme-add-face 'w3m-tab-unselected-retrieving-face)
  (custom-theme-add-face 'wg-brace-face)
  (custom-theme-add-face 'wg-command-face)
  (custom-theme-add-face 'wg-current-workgroup-face)
  (custom-theme-add-face 'wg-divider-face)
  (custom-theme-add-face 'wg-filename-face)
  (custom-theme-add-face 'wg-frame-face)
  (custom-theme-add-face 'wg-message-face)
  (custom-theme-add-face 'wg-mode-line-face)
  (custom-theme-add-face 'wg-other-workgroup-face)
  (custom-theme-add-face 'wg-previous-workgroup-face)
  (custom-theme-add-face 'wgrep-delete-face)
  (custom-theme-add-face 'wgrep-face)
  (custom-theme-add-face 'which-func)
  (custom-theme-add-face 'wl-highlight-folder-few-face)
  (custom-theme-add-face 'wl-highlight-folder-many-face)
  (custom-theme-add-face 'wl-highlight-folder-path-face)
  (custom-theme-add-face 'wl-highlight-folder-unknown-face)
  (custom-theme-add-face 'wl-highlight-folder-unread-face)
  (custom-theme-add-face 'wl-highlight-folder-zero-face)
  (custom-theme-add-face 'wl-highlight-message-citation-header)
  (custom-theme-add-face 'wl-highlight-message-cited-text-1)
  (custom-theme-add-face 'wl-highlight-message-cited-text-2)
  (custom-theme-add-face 'wl-highlight-message-cited-text-3)
  (custom-theme-add-face 'wl-highlight-message-cited-text-4)
  (custom-theme-add-face 'wl-highlight-message-header-contents)
  (custom-theme-add-face 'wl-highlight-message-header-contents-face)
  (custom-theme-add-face 'wl-highlight-message-headers-face)
  (custom-theme-add-face 'wl-highlight-message-important-header-contents)
  (custom-theme-add-face 'wl-highlight-message-important-header-contents2)
  (custom-theme-add-face 'wl-highlight-message-signature)
  (custom-theme-add-face 'wl-highlight-message-unimportant-header-contents)
  (custom-theme-add-face 'wl-highlight-summary-answered-face)
  (custom-theme-add-face 'wl-highlight-summary-displaying-face)
  (custom-theme-add-face 'wl-highlight-summary-disposed-face)
  (custom-theme-add-face 'wl-highlight-summary-new-face)
  (custom-theme-add-face 'wl-highlight-summary-normal-face)
  (custom-theme-add-face 'wl-highlight-summary-refiled-face)
  (custom-theme-add-face 'wl-highlight-summary-thread-top-face)
  (custom-theme-add-face 'wl-highlight-thread-indent-face)
  )

(provide 'my-theme)
