(setq savehist-minibuffer-history-variables
	  bookmark-history
	  buffer-name-history
	  c-read-offset-history
	  c-set-style-history
	  coding-system-history
	  compile-history
	  dired-regexp-history
	  dired-shell-command-history
	  ediff-filtering-regexp-history
	  erc-nick-history-list
	  erc-server-history-list
	  extended-command-history
	  face-name-history
	  file-name-history
	  find-args-history
	  find-tag-history
	  frame-name-history
	  grep-files-history
	  grep-history
	  grep-regexp-history
	  ido-buffer-history
	  ido-file-history
	  input-method-history
	  iswitchb-history
	  locate-history-list
	  minibuffer-history
	  minibuffer-history-search-history
	  project-buffer-regexp-history
	  query-replace-history
	  read-expression-history
	  regexp-history
	  regexp-search-ring
	  search-ring
	  shell-command-history
	  ;; svn-switch-history
	  trac-wiki-comment-history
	  trac-wiki-page-history
	  trac-wiki-project-history
	  w32-find-dired-pattern-history
	  woman-topic-history
)
