(deftheme my-default-dark
  "Created 2014-04-08.")

(custom-theme-set-variables
 'my-default-dark
 '(my-default-font-size 120))

(custom-theme-set-faces
 'my-default-dark
 '(default ((t (:width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#bebebc" :background "#242426" :stipple nil :inherit nil))))
 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:slant italic :weight bold))))
 '(error ((t (:weight bold :foreground-color:pink))))
 '(fixed-pitch ((t (:inherit (default)))))
 '(italic ((((supports :slant italic)) (:slant italic)) (((supports :underline t)) (:underline (:color foreground-color :style line))) (t (:slant italic))))
 '(underline ((t (:underline (:color foreground-color :style line)))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(fringe ((t (:background "#212526"))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(highlight ((t (:background "#4d3400"))))
 '(hover-highlight ((t nil)))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(menu ((((type tty)) (:inverse-video t)) (((type x-toolkit)) nil) (t (:inverse-video t))))
 '(mouse ((t nil)))
 '(paren ((t nil)))
 '(trailing-whitespace ((t (:background "#a40000"))))
 '(buffer-menu-buffer ((t (:weight bold))))
 '(border ((t nil)))
 '(button ((t (:inherit (link)))))
 '(cursor ((t (:background "red"))))
 '(escape-glyph-face ((t nil)))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#729fcf"))))
 '(minibuffer-prompt ((t (:foreground "#b4fa70"))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#242426" :background "#d3d7cf"))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color nil :style released-button) :foreground "#eeeeec" :background "#555753" :inherit (mode-line)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(region ((t (:background "#555753"))))
 '(scroll-bar ((t nil)))
 '(secondary-selection ((t (:background "#204a87"))))
 '(tool-bar ((t (:box (:line-width 1 :color nil :style released-button) :foreground "black" :background "grey75"))))
 '(apt-utils-broken ((t nil)))
 '(apt-utils-description ((t nil)))
 '(apt-utils-field-contents ((t nil)))
 '(apt-utils-field-keyword ((t nil)))
 '(apt-utils-normal-package ((t nil)))
 '(apt-utils-summary ((t nil)))
 '(apt-utils-version ((t nil)))
 '(apt-utils-virtual-package ((t nil)))
 '(breakpoint-disabled-bitmap ((t nil)))
 '(breakpoint-enabled-bitmap ((t nil)))
 '(calendar-today ((t (:underline (:color foreground-color :style line)))))
 '(change-log-date ((t (:inherit (font-lock-string-face)))))
 '(circe-highlight-nick-face ((t nil)))
 '(circe-my-message-face ((t nil)))
 '(circe-originator-face ((t nil)))
 '(circe-prompt-face ((t nil)))
 '(circe-server-face ((t nil)))
 '(comint-highlight-input ((t (:foreground "goldenrod1" :weight bold))))
 '(comint-highlight-prompt ((t (:inherit (minibuffer-prompt)))))
 '(compilation-info ((t (:inherit (success)))))
 '(compilation-warning ((t (:inherit (warning)))))
 '(cscope-line-face ((((class color) (background dark)) (:foreground "green")) (((class color) (background light)) (:foreground "black")) (t (:bold nil))))
 '(cua-rectangle ((t (:foreground "white" :background "maroon" :inherit (region)))))
 '(custom-button ((t (:box (:line-width 2 :color nil :style released-button) :foreground "black" :background "lightgrey"))))
 '(custom-button-pressed ((t (:box (:line-width 2 :color nil :style pressed-button) :foreground "black" :background "lightgrey"))))
 '(custom-changed ((((min-colors 88) (class color)) (:background "blue1" :foreground "white")) (((class color)) (:background "blue" :foreground "white")) (t (:slant italic))))
 '(custom-comment ((((type tty)) (:foreground "black" :background "yellow3")) (((class grayscale color) (background light)) (:background "gray85")) (((class grayscale color) (background dark)) (:background "dim gray")) (t (:slant italic))))
 '(custom-comment-tag ((((class color) (background dark)) (:foreground "gray80")) (((class color) (background light)) (:foreground "blue4")) (((class grayscale) (background light)) (:slant italic :weight bold :foreground "DimGray")) (((class grayscale) (background dark)) (:slant italic :weight bold :foreground "LightGray")) (t (:weight bold))))
 '(custom-documentation ((t nil)))
 '(custom-group-tag ((t (:height 1.2 :weight bold :foreground "light blue" :inherit (variable-pitch)))))
 '(custom-group-tag-1 ((t (:height 1.2 :weight bold :foreground "pink" :inherit (variable-pitch)))))
 '(custom-invalid ((((class color)) (:background "red1" :foreground "yellow1")) (t (:underline (:color foreground-color :style line) :slant italic :weight bold))))
 '(custom-link ((t (:inherit (link)))))
 '(custom-modified ((((min-colors 88) (class color)) (:background "blue1" :foreground "white")) (((class color)) (:background "blue" :foreground "white")) (t (:slant italic))))
 '(custom-rogue ((((class color)) (:background "black" :foreground "pink")) (t (:underline (:color foreground-color :style line)))))
 '(custom-saved ((t (:underline (:color foreground-color :style line)))))
 '(custom-set ((((min-colors 88) (class color)) (:background "white" :foreground "blue1")) (((class color)) (:background "white" :foreground "blue")) (t (:slant italic))))
 '(custom-state ((((class color) (background dark)) (:foreground "lime green")) (((class color) (background light)) (:foreground "dark green"))))
 '(custom-tag ((t nil)))
 '(custom-variable-button ((t (:weight bold :underline (:color foreground-color :style line)))))
 '(custom-variable-tag ((((class color) (background dark)) (:weight bold :foreground "light blue")) (((min-colors 88) (class color) (background light)) (:weight bold :foreground "blue1")) (((class color) (background light)) (:weight bold :foreground "blue")) (t (:weight bold))))
 '(diary ((((min-colors 88) (class color) (background light)) (:foreground "red1")) (((class color) (background light)) (:foreground "red")) (((min-colors 88) (class color) (background dark)) (:foreground "yellow1")) (((class color) (background dark)) (:foreground "yellow")) (t (:weight bold))))
 '(dictionary-button ((t nil)))
 '(dictionary-reference ((t nil)))
 '(dictionary-word-entry ((t nil)))
 '(diff-added-face ((t (:background "#335533" :inherit (diff-changed)))))
 '(diff-context-face ((t (:inherit (shadow)))))
 '(diff-file-header-face ((t (:weight bold :background "grey60"))))
 '(diff-header-face ((t (:background "grey45"))))
 '(diff-hunk-header-face ((t (:inherit (diff-header)))))
 '(diff-index-face ((t (:inherit (diff-file-header)))))
 '(diff-refine-added ((t (:background "#22aa22" :inherit (diff-refine-change)))))
 '(diff-refine-change-face ((t nil)))
 '(diff-removed-face ((t (:background "#553333" :inherit (diff-changed)))))
 '(diredp-compressed-file-suffix ((t nil)))
 '(diredp-date-time ((t nil)))
 '(diredp-default ((t nil)))
 '(diredp-deletion ((t nil)))
 '(diredp-deletion-file-name ((t nil)))
 '(diredp-dir-heading ((t nil)))
 '(diredp-dir-priv ((t nil)))
 '(diredp-display-msg ((t nil)))
 '(diredp-exec-priv ((t nil)))
 '(diredp-executable-tag ((t nil)))
 '(diredp-file-name ((t nil)))
 '(diredp-file-suffix ((t nil)))
 '(diredp-flag-mark ((t nil)))
 '(diredp-flag-mark-line ((t nil)))
 '(diredp-ignored-file-name ((t nil)))
 '(diredp-link-priv ((t nil)))
 '(diredp-no-priv ((t nil)))
 '(diredp-number ((t nil)))
 '(diredp-other-priv ((t nil)))
 '(diredp-rare-priv ((t nil)))
 '(diredp-read-priv ((t nil)))
 '(diredp-symlink ((t nil)))
 '(diredp-write-priv ((t nil)))
 '(ediff-current-diff-A ((t (:background "#555753"))))
 '(ediff-current-diff-B ((t (:background "#555753"))))
 '(ediff-current-diff-C ((t nil)))
 '(ediff-old-diff-A ((t nil)))
 '(ediff-old-diff-B ((t nil)))
 '(ediff-old-diff-C ((t nil)))
 '(emms-pbi-current ((t nil)))
 '(emms-pbi-mark-marked ((t nil)))
 '(emms-pbi-song ((t nil)))
 '(erc-action-face ((t (:weight bold))))
 '(erc-bold-face ((t (:weight bold))))
 '(erc-current-nick-face ((t (:weight bold :foreground "DarkTurquoise"))))
 '(erc-dangerous-host-face ((t (:foreground "red"))))
 '(erc-default-face ((t nil)))
 '(erc-direct-msg-face ((t (:foreground "IndianRed"))))
 '(erc-error-face ((t (:foreground "red"))))
 '(erc-fool-face ((t (:foreground "dim gray"))))
 '(erc-highlight-face ((t nil)))
 '(erc-input-face ((t (:foreground "brown"))))
 '(erc-keyword-face ((t (:weight bold :foreground "pale green"))))
 '(erc-my-nick-face ((t (:weight bold :foreground "brown"))))
 '(erc-nick-default-face ((t (:weight bold))))
 '(erc-nick-msg-face ((t (:weight bold :foreground "IndianRed"))))
 '(erc-notice-face ((t (:weight bold :foreground "SlateBlue"))))
 '(erc-pal-face ((t (:weight bold :foreground "Magenta"))))
 '(erc-prompt-face ((t (:weight bold :foreground "Black" :background "lightBlue2"))))
 '(erc-timestamp-face ((t nil)))
 '(erc-underline-face ((t (:underline (:color foreground-color :style line)))))
 '(eshell-ls-archive ((t nil)))
 '(eshell-ls-backup ((t nil)))
 '(eshell-ls-clutter ((t nil)))
 '(eshell-ls-directory ((t nil)))
 '(eshell-ls-executable ((t nil)))
 '(eshell-ls-missing ((t nil)))
 '(eshell-ls-product ((t nil)))
 '(eshell-ls-special ((t nil)))
 '(eshell-ls-symlink ((t nil)))
 '(eshell-ls-unreadable ((t nil)))
 '(eshell-prompt ((t nil)))
 '(fancy-widget-button ((t nil)))
 '(fancy-widget-button-highlight ((t nil)))
 '(fancy-widget-button-pressed ((t nil)))
 '(fancy-widget-button-pressed-highlight ((t nil)))
 '(fancy-widget-documentation ((t nil)))
 '(fancy-widget-field ((t nil)))
 '(fancy-widget-inactive ((t nil)))
 '(fancy-widget-single-line-field ((t nil)))
 '(flyspell-duplicate ((t (:underline (:color "#fcaf3e" :style line)))))
 '(flyspell-incorrect ((t (:underline (:color "#ef2929" :style line)))))
 '(font-latex-bold ((t nil)))
 '(font-latex-sedate ((t nil)))
 '(font-latex-title-4 ((t nil)))
 '(font-latex-warning ((t nil)))
 '(font-lock-builtin-face ((t (:foreground "#ad7fa8"))))
 '(font-lock-comment-delimiter-face ((t (:inherit 'font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#53b216" :slant italic :inherit (default)))))
 '(font-lock-constant-face ((t (:foreground "#e6a8df"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-doc-string-face ((t nil)))
 '(font-lock-function-name-face ((t (:foreground "#fce94f"))))
 '(font-lock-keyword-face ((t (:slant italic :foreground "#b4fa70"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-pseudo-keyword-face ((t nil)))
 '(font-lock-string-face ((t (:foreground "#e9b96e"))))
 '(font-lock-type-face ((t (:foreground "#8cc4ff"))))
 '(font-lock-variable-name-face ((t (:foreground "#fcaf3e"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(gnus-cite-1-face ((t nil)))
 '(gnus-cite-10-face ((t nil)))
 '(gnus-cite-11-face ((t nil)))
 '(gnus-cite-2-face ((t nil)))
 '(gnus-cite-3-face ((t nil)))
 '(gnus-cite-4-face ((t nil)))
 '(gnus-cite-5-face ((t nil)))
 '(gnus-cite-6-face ((t nil)))
 '(gnus-cite-7-face ((t nil)))
 '(gnus-cite-8-face ((t nil)))
 '(gnus-cite-9-face ((t nil)))
 '(gnus-group-mail-1-empty-face ((t nil)))
 '(gnus-group-mail-1-face ((t nil)))
 '(gnus-group-mail-2-empty-face ((t nil)))
 '(gnus-group-mail-2-face ((t nil)))
 '(gnus-group-mail-3-empty-face ((t nil)))
 '(gnus-group-mail-3-face ((t nil)))
 '(gnus-group-mail-4-empty-face ((t nil)))
 '(gnus-group-mail-4-face ((t nil)))
 '(gnus-group-mail-5-empty-face ((t nil)))
 '(gnus-group-mail-5-face ((t nil)))
 '(gnus-group-mail-6-empty-face ((t nil)))
 '(gnus-group-mail-6-face ((t nil)))
 '(gnus-group-mail-low-empty-face ((t nil)))
 '(gnus-group-mail-low-face ((t nil)))
 '(gnus-group-news-1-empty-face ((t nil)))
 '(gnus-group-news-1-face ((t nil)))
 '(gnus-group-news-2-empty-face ((t nil)))
 '(gnus-group-news-2-face ((t nil)))
 '(gnus-group-news-3-empty-face ((t nil)))
 '(gnus-group-news-3-face ((t nil)))
 '(gnus-group-news-4-empty-face ((t nil)))
 '(gnus-group-news-4-face ((t nil)))
 '(gnus-group-news-5-empty-face ((t nil)))
 '(gnus-group-news-5-face ((t nil)))
 '(gnus-group-news-6-empty-face ((t nil)))
 '(gnus-group-news-6-face ((t nil)))
 '(gnus-group-news-low-empty-face ((t nil)))
 '(gnus-group-news-low-face ((t nil)))
 '(gnus-header-content-face ((t nil)))
 '(gnus-header-from-face ((t nil)))
 '(gnus-header-name-face ((t nil)))
 '(gnus-header-newsgroups-face ((t nil)))
 '(gnus-header-subject-face ((t nil)))
 '(gnus-signature-face ((t nil)))
 '(gnus-summary-cancelled-face ((t nil)))
 '(gnus-summary-high-ancient-face ((t nil)))
 '(gnus-summary-high-read-face ((t nil)))
 '(gnus-summary-high-ticked-face ((t nil)))
 '(gnus-summary-high-unread-face ((t nil)))
 '(gnus-summary-low-ancient-face ((t nil)))
 '(gnus-summary-low-read-face ((t nil)))
 '(gnus-summary-low-ticked-face ((t nil)))
 '(gnus-summary-low-unread-face ((t nil)))
 '(gnus-summary-normal-ancient-face ((t nil)))
 '(gnus-summary-normal-read-face ((t nil)))
 '(gnus-summary-normal-ticked-face ((t nil)))
 '(gnus-summary-normal-unread-face ((t nil)))
 '(gnus-summary-selected-face ((t nil)))
 '(gnus-x-face ((t nil)))
 '(helm-ff-directory ((t (:background "LightGray" :foreground "DarkRed"))))
 '(helm-ff-executable ((t (:foreground "green"))))
 '(helm-ff-file ((t (:inherit (font-lock-builtin-face)))))
 '(helm-grep-file ((t (:underline (:color foreground-color :style line) :foreground "BlueViolet"))))
 '(helm-grep-match ((t (:inherit (match)))))
 '(helm-header ((t (:inherit (header-line)))))
 '(helm-match ((t (:inherit (match)))))
 '(helm-selection ((t (:underline (:color foreground-color :style line) :foreground "black" :background "goldenrod1"))))
 '(helm-selection-line ((t (:underline (:color foreground-color :style line) :background "IndianRed4"))))
 '(helm-source-header ((((background dark)) (:family "Sans Serif" :height 1.3 :weight bold :foreground "white" :background "#22083397778B")) (((background light)) (:family "Sans Serif" :height 1.3 :weight bold :foreground "black" :background "#abd7f0"))))
 '(helm-visible-mark ((((min-colors 88) (background dark)) (:foreground "black" :background "green1")) (((background dark)) (:foreground "black" :background "green")) (((background light)) (:background "#d1f5ea")) (((min-colors 88)) (:background "green1")) (t (:background "green"))))
 '(help-argument-name ((t (:inherit (italic)))))
 '(hi-blue ((((background dark)) (:foreground "black" :background "light blue")) (t (:background "light blue"))))
 '(hi-green ((((min-colors 88) (background dark)) (:foreground "black" :background "green1")) (((background dark)) (:foreground "black" :background "green")) (((min-colors 88)) (:background "green1")) (t (:background "green"))))
 '(hi-pink ((((background dark)) (:foreground "black" :background "pink")) (t (:background "pink"))))
 '(hi-yellow ((((min-colors 88) (background dark)) (:foreground "black" :background "yellow1")) (((background dark)) (:foreground "black" :background "yellow")) (((min-colors 88)) (:background "yellow1")) (t (:background "yellow"))))
 '(highlight-current-line ((t nil)))
 '(hl-line ((t (:inherit (highlight)))))
 '(holiday ((((class color) (background light)) (:background "pink")) (((class color) (background dark)) (:background "chocolate4")) (t (:inverse-video t))))
 '(ibuffer-deletion ((t nil)))
 '(ibuffer-help-buffer ((t nil)))
 '(ibuffer-marked ((t nil)))
 '(ibuffer-special-buffer ((t nil)))
 '(icompletep-choices ((t nil)))
 '(icompletep-determined ((t nil)))
 '(icompletep-keys ((t nil)))
 '(icompletep-nb-candidates ((t nil)))
 '(ido-first-match ((t (:weight bold))))
 '(ido-only-match ((((class color)) (:foreground "ForestGreen")) (t (:slant italic))))
 '(ido-subdir ((((min-colors 88) (class color)) (:foreground "red1")) (((class color)) (:foreground "red")) (t (:underline (:color foreground-color :style line)))))
 '(imaxima-latex-error ((t nil)))
 '(info-header-node ((t (:inherit (info-node)))))
 '(info-header-xref ((t (:inherit (info-xref)))))
 '(info-menu-5 ((t nil)))
 '(info-menu-header ((t (:weight bold :inherit (variable-pitch)))))
 '(info-menu-star ((t nil)))
 '(info-node ((t (:weight bold :slant italic :foreground "white"))))
 '(info-title-4 ((t (:weight bold :inherit (variable-pitch)))))
 '(info-xref ((t (:inherit (link)))))
 '(info-xref-visited ((t (:inherit (link-visited info-xref)))))
 '(isearch ((t (:foreground "#eeeeec" :background "#ce5c00"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(jabber-chat-prompt-foreign ((t nil)))
 '(jabber-chat-prompt-local ((t nil)))
 '(jabber-rare-time-face ((t nil)))
 '(jabber-roster-user-away ((t nil)))
 '(jabber-roster-user-chatty ((t nil)))
 '(jabber-roster-user-dnd ((t nil)))
 '(jabber-roster-user-error ((t nil)))
 '(jabber-roster-user-offline ((t nil)))
 '(jabber-roster-user-online ((t nil)))
 '(jabber-roster-user-xa ((t nil)))
 '(jabber-title-large ((t nil)))
 '(jabber-title-medium ((t nil)))
 '(jabber-title-small ((t nil)))
 '(jde-java-font-lock-constant-face ((t nil)))
 '(jde-java-font-lock-doc-tag-face ((t nil)))
 '(jde-java-font-lock-link-face ((t nil)))
 '(jde-java-font-lock-modifier-face ((t nil)))
 '(jde-java-font-lock-number-face ((t nil)))
 '(jde-java-font-lock-operator-face ((t nil)))
 '(jde-java-font-lock-package-face ((t nil)))
 '(keywiz-command-face ((t (:inherit (quote variable-pitch) :height 1.2 :weight bold :foreground "Blue"))))
 '(keywiz-right-face ((t (:foreground "dark green"))))
 '(keywiz-wrong-face ((t (:foreground "Red"))))
 '(lazy-highlight ((t (:background "#8f5902"))))
 '(magit-branch ((t (:inherit (magit-header)))))
 '(magit-item-highlight ((t (:inherit (highlight)))))
 '(magit-section-title ((t (:inherit (magit-header)))))
 '(makefile-shell ((t nil)))
 '(makefile-space ((t nil)))
 '(message-cited-text-face ((t nil)))
 '(message-header-cc-face ((t nil)))
 '(message-header-from-face ((t nil)))
 '(message-header-name-face ((t nil)))
 '(message-header-newsgroups-face ((t nil)))
 '(message-header-other-face ((t nil)))
 '(message-header-subject-face ((t nil)))
 '(message-header-to-face ((t nil)))
 '(message-header-xheader-face ((t nil)))
 '(message-mml-face ((t nil)))
 '(message-separator-face ((t nil)))
 '(minimap-active-region-background ((t nil)))
 '(mm/master-face ((t nil)))
 '(mm/mirror-face ((t nil)))
 '(org-agenda-clocking ((t nil)))
 '(org-agenda-date ((t nil)))
 '(org-agenda-date-today ((t nil)))
 '(org-agenda-date-weekend ((t nil)))
 '(org-agenda-structure ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8)) (:bold t :foreground "blue")) (t (:bold t))))
 '(org-archived ((t (:inherit (shadow)))))
 '(org-checkbox ((t (:inherit (bold)))))
 '(org-date ((t (:underline (:color foreground-color :style line) :foreground "Cyan"))))
 '(org-deadline-announce ((t nil)))
 '(org-document-title ((((class color) (background light)) (:weight bold :foreground "midnight blue")) (((class color) (background dark)) (:weight bold :foreground "pale turquoise")) (t (:weight bold))))
 '(org-done ((((class color) (min-colors 16) (background light)) (:bold t :foreground "ForestGreen")) (((class color) (min-colors 16) (background dark)) (:bold t :foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:bold t))))
 '(org-formula ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:foreground "red")) (t (:italic t :bold t))))
 '(org-headline-done ((((class color) (min-colors 16) (background light)) (:foreground "RosyBrown")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSalmon")) (((class color) (min-colors 8) (background light)) (:bold nil))))
 '(org-hide ((t (:foreground "#202a24"))))
 '(org-level-1 ((t (:inherit (outline-1)))))
 '(org-level-2 ((t (:inherit (outline-2)))))
 '(org-level-3 ((t (:inherit (outline-3)))))
 '(org-level-4 ((t (:inherit (outline-4)))))
 '(org-level-5 ((t (:inherit (outline-5)))))
 '(org-level-6 ((t (:inherit (outline-6)))))
 '(org-level-7 ((t (:inherit (outline-7)))))
 '(org-level-8 ((t (:inherit (outline-8)))))
 '(org-link ((t (:inherit (link)))))
 '(org-scheduled ((((class color) (min-colors 88) (background light)) (:foreground "DarkGreen")) (((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:italic t :bold t))))
 '(org-scheduled-previously ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:bold t :foreground "red")) (t (:bold t))))
 '(org-scheduled-today ((((class color) (min-colors 88) (background light)) (:foreground "DarkGreen")) (((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:italic t :bold t))))
 '(org-special-keyword ((t (:inherit (font-lock-keyword-face)))))
 '(org-table ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8) (background light)) (:foreground "blue")) (((class color) (min-colors 8) (background dark)) nil)))
 '(org-tag ((t (:bold t))))
 '(org-time-grid ((((class color) (min-colors 16) (background light)) (:foreground "DarkGoldenrod")) (((class color) (min-colors 16) (background dark)) (:foreground "LightGoldenrod")) (((class color) (min-colors 8)) (:weight light :foreground "yellow"))))
 '(org-todo ((((class color) (min-colors 16) (background light)) (:bold t :foreground "Red1")) (((class color) (min-colors 16) (background dark)) (:bold t :foreground "Pink")) (((class color) (min-colors 8) (background light)) (:bold t :foreground "red")) (((class color) (min-colors 8) (background dark)) (:bold t :foreground "red")) (t (:bold t :inverse-video t))))
 '(org-upcoming-deadline ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:bold t :foreground "red")) (t (:bold t))))
 '(org-warning ((t (:inherit (font-lock-warning-face)))))
 '(outline-1 ((t (:inherit (font-lock-function-name-face)))))
 '(outline-2 ((t (:inherit (font-lock-variable-name-face)))))
 '(outline-3 ((t (:inherit (font-lock-keyword-face)))))
 '(outline-4 ((t (:inherit (font-lock-comment-face)))))
 '(outline-5 ((t (:inherit (font-lock-type-face)))))
 '(outline-6 ((t (:inherit (font-lock-constant-face)))))
 '(outline-7 ((t (:inherit (font-lock-builtin-face)))))
 '(outline-8 ((t (:inherit (font-lock-string-face)))))
 '(rainbow-delimiters-depth-1-face ((((background light)) (:foreground "#707183")) (((background dark)) (:foreground "grey55"))))
 '(rainbow-delimiters-depth-10-face ((t nil)))
 '(rainbow-delimiters-depth-11-face ((t nil)))
 '(rainbow-delimiters-depth-12-face ((t nil)))
 '(rainbow-delimiters-depth-2-face ((((background light)) (:foreground "#7388d6")) (((background dark)) (:foreground "#93a8c6"))))
 '(rainbow-delimiters-depth-3-face ((((background light)) (:foreground "#909183")) (((background dark)) (:foreground "#b0b1a3"))))
 '(rainbow-delimiters-depth-4-face ((((background light)) (:foreground "#709870")) (((background dark)) (:foreground "#97b098"))))
 '(rainbow-delimiters-depth-5-face ((((background light)) (:foreground "#907373")) (((background dark)) (:foreground "#aebed8"))))
 '(rainbow-delimiters-depth-6-face ((((background light)) (:foreground "#6276ba")) (((background dark)) (:foreground "#b0b0b3"))))
 '(rainbow-delimiters-depth-7-face ((((background light)) (:foreground "#858580")) (((background dark)) (:foreground "#90a890"))))
 '(rainbow-delimiters-depth-8-face ((((background light)) (:foreground "#80a880")) (((background dark)) (:foreground "#a2b6da"))))
 '(rainbow-delimiters-depth-9-face ((((background light)) (:foreground "#887070")) (((background dark)) (:foreground "#9cb6ad"))))
 '(rcirc-bright-nick ((t (:foreground "Aquamarine"))))
 '(rcirc-dim-nick ((t (:inherit (default)))))
 '(rcirc-mode-line-nick ((t nil)))
 '(rcirc-my-nick ((t (:foreground "LightSkyBlue"))))
 '(rcirc-nick-in-message ((t (:foreground "Cyan1"))))
 '(rcirc-other-nick ((t (:foreground "LightGoldenrod"))))
 '(rcirc-prompt ((t (:foreground "cyan1"))))
 '(rcirc-server ((t (:foreground "chocolate1"))))
 '(rcirc-server-prefix ((t (:inherit (rcirc-server)))))
 '(rcirc-timestamp ((t (:inherit (default)))))
 '(rst-level-1-face ((t nil)))
 '(rst-level-2-face ((t nil)))
 '(rst-level-3-face ((t nil)))
 '(rst-level-4-face ((t nil)))
 '(setnu-line-number ((t nil)))
 '(show-paren-match ((t (:background "steelblue3"))))
 '(show-paren-mismatch ((t (:foreground "white" :background "purple"))))
 '(speedbar-button-face ((t (:foreground "green3"))))
 '(speedbar-directory-face ((t (:foreground "light blue"))))
 '(speedbar-file-face ((t (:foreground "cyan"))))
 '(speedbar-highlight-face ((t (:background "sea green"))))
 '(speedbar-tag-face ((t (:foreground "yellow"))))
 '(strokes-char-face ((t nil)))
 '(todoo-item-assigned-header-face ((t nil)))
 '(todoo-item-header-face ((t nil)))
 '(todoo-sub-item-header-face ((t nil)))
 '(tuareg-font-lock-governing-face ((t nil)))
 '(tuareg-font-lock-interactive-error-face ((t nil)))
 '(tuareg-font-lock-interactive-output-face ((t nil)))
 '(tuareg-font-lock-operator-face ((t nil)))
 '(twittering-uri-face ((t nil)))
 '(twittering-username-face ((t nil)))
 '(w3m-anchor-face ((t nil)))
 '(w3m-arrived-anchor-face ((t nil)))
 '(w3m-form-button-face ((t nil)))
 '(w3m-form-button-mouse-face ((t nil)))
 '(w3m-form-button-pressed-face ((t nil)))
 '(w3m-form-face ((t nil)))
 '(w3m-image-face ((t nil)))
 '(w3m-tab-background-face ((t nil)))
 '(w3m-tab-selected-face ((t nil)))
 '(w3m-tab-selected-retrieving-face ((t nil)))
 '(w3m-tab-unselected-face ((t nil)))
 '(w3m-tab-unselected-retrieving-face ((t nil)))
 '(wg-brace-face ((t nil)))
 '(wg-command-face ((t nil)))
 '(wg-current-workgroup-face ((t nil)))
 '(wg-divider-face ((t nil)))
 '(wg-filename-face ((t nil)))
 '(wg-frame-face ((t nil)))
 '(wg-message-face ((t nil)))
 '(wg-mode-line-face ((t nil)))
 '(wg-other-workgroup-face ((t nil)))
 '(wg-previous-workgroup-face ((t nil)))
 '(wgrep-delete-face ((((class color) (background dark)) (:foreground "pink" :background "SlateGray1")) (((class color) (background light)) (:foreground "pink" :background "ForestGreen")) (t nil)))
 '(wgrep-face ((((class color) (background dark)) (:foreground "Black" :background "SlateGray1")) (((class color) (background light)) (:foreground "white" :background "ForestGreen")) (t nil)))
 '(which-func ((t (:foreground "Blue1"))))
 '(wl-highlight-folder-few-face ((t nil)))
 '(wl-highlight-folder-many-face ((t nil)))
 '(wl-highlight-folder-path-face ((t nil)))
 '(wl-highlight-folder-unknown-face ((t nil)))
 '(wl-highlight-folder-unread-face ((t nil)))
 '(wl-highlight-folder-zero-face ((t nil)))
 '(wl-highlight-message-citation-header ((t nil)))
 '(wl-highlight-message-cited-text-1 ((t nil)))
 '(wl-highlight-message-cited-text-2 ((t nil)))
 '(wl-highlight-message-cited-text-3 ((t nil)))
 '(wl-highlight-message-cited-text-4 ((t nil)))
 '(wl-highlight-message-header-contents ((t nil)))
 '(wl-highlight-message-header-contents-face ((t nil)))
 '(wl-highlight-message-headers-face ((t nil)))
 '(wl-highlight-message-important-header-contents ((t nil)))
 '(wl-highlight-message-important-header-contents2 ((t nil)))
 '(wl-highlight-message-signature ((t nil)))
 '(wl-highlight-message-unimportant-header-contents ((t nil)))
 '(wl-highlight-summary-answered-face ((t nil)))
 '(wl-highlight-summary-displaying-face ((t nil)))
 '(wl-highlight-summary-disposed-face ((t nil)))
 '(wl-highlight-summary-new-face ((t nil)))
 '(wl-highlight-summary-normal-face ((t nil)))
 '(wl-highlight-summary-refiled-face ((t nil)))
 '(wl-highlight-summary-thread-top-face ((t nil)))
 '(wl-highlight-thread-indent-face ((t nil))))

(provide-theme 'my-default-dark)
