(deftheme my-solarized-dark
  "solarized dark theme for deftheme system")

(custom-theme-set-faces
 'my-solarized-dark
 `(default ((t (:family ,my-default-font-name :foundry "apple" :width normal :height ,(* 10 my-default-font-size) :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#708183" :background "#202428" :stipple nil :inherit nil))))
 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:slant italic :weight bold))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(italic ((((supports :slant italic)) (:slant italic)) (((supports :underline t)) (:underline (:color foreground-color :style line))) (t (:slant italic))))
 '(underline ((((supports :underline t)) (:underline (:color foreground-color :style line))) (((supports :weight bold)) (:weight bold)) (t (:underline (:color foreground-color :style line)))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(fringe ((t (:foreground "#465a61" :background "#0a2832"))))
 '(header-line ((t (:weight normal :slant normal :underline nil :box nil :inverse-video t :foreground "#708183" :background "#0a2832" :inherit (mode-line)))))
 '(highlight ((t (:background "#1a3842"))))
 '(hover-highlight ((t nil)))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1"))
		  (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue4"))
		  (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow"))
		  (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue"))
		  (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(menu ((t (:inverse-video t :foreground "#708183" :background "#0a2832"))))
 '(mouse ((t nil)))
 '(paren ((t nil)))
 '(trailing-whitespace ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#260007" :background "red1"))))
 '(buffer-menu-buffer ((t (:weight bold))))
 '(border ((t nil)))
 '(button ((t (:inherit (link)))))
 '(cursor ((t (:foreground "#042028" :background "#708183"))))
 '(escape-glyph-face ((t (:foreground "#c60007"))))
 '(link ((t (:weight normal :slant normal :underline (:color foreground-color :style line) :inverse-video nil :foreground "#5859b7"))))
 '(minibuffer-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(mode-line ((t (:weight normal :slant normal :underline nil :box nil :inverse-video t :foreground "#81908f" :background "#0a2832"))))
 '(mode-line-inactive ((t (:weight normal :slant normal :underline nil :box nil :inverse-video t :foreground "#42575f" :background "#0a2832" :inherit (mode-line)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button)))
						(t (:inherit (highlight)))))
 '(region ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#465a61" :background "#042028"))))
 '(scroll-bar ((t nil)))
 '(secondary-selection ((t (:background "#0a2832"))))
 '(tool-bar ((default (:foreground "black" :box (:line-width 1 :color nil :style released-button))) (((type x w32 ns) (class color)) (:background "grey75")) (((type x) (class mono)) (:background "grey"))))
 '(apt-utils-broken ((t nil)))
 '(apt-utils-description ((t nil)))
 '(apt-utils-field-contents ((t nil)))
 '(apt-utils-field-keyword ((t nil)))
 '(apt-utils-normal-package ((t nil)))
 '(apt-utils-summary ((t nil)))
 '(apt-utils-version ((t nil)))
 '(apt-utils-virtual-package ((t nil)))
 '(breakpoint-disabled-bitmap ((t nil)))
 '(breakpoint-enabled-bitmap ((t nil)))
 '(calendar-today ((t (:underline (:color foreground-color :style line)))))
 '(change-log-date ((t (:inherit (font-lock-string-face)))))
 '(circe-highlight-nick-face ((t nil)))
 '(circe-my-message-face ((t nil)))
 '(circe-originator-face ((t nil)))
 '(circe-prompt-face ((t nil)))
 '(circe-server-face ((t nil)))
 '(comint-highlight-input ((t (:weight bold))))
 '(comint-highlight-prompt ((t (:foreground "#2075c7" :inherit (minibuffer-prompt)))))
 '(compilation-info ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#729a05" :inherit (success)))))
 '(compilation-warning ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#9d4632" :inherit (warning)))))
 '(cscope-line-face ((((class color) (background dark)) (:foreground "green")) (((class color) (background light)) (:foreground "black")) (t (:bold nil))))
 '(cua-rectangle ((t nil)))
 '(custom-button ((t (:box (:line-width 2 :color nil :style released-button) :foreground "#81908f" :background "#0a2832"))))
 '(custom-button-pressed ((t (:weight normal :slant normal :underline nil :box (:line-width 2 :color nil :style pressed-button) :inverse-video t :foreground "#81908f" :background "#0a2832" :inherit (custom-button-mouse)))))
 '(custom-changed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#2075c7" :background "#fcf4dc"))))
 '(custom-comment ((t (:foreground "#81908f" :background "#0a2832"))))
 '(custom-comment-tag ((t (:foreground "#81908f" :background "#0a2832"))))
 '(custom-documentation ((t (:inherit (default)))))
 '(custom-group-tag ((t (:height 1.2 :weight bold :foreground "#81908f" :inherit (variable-pitch)))))
 '(custom-group-tag-1 ((default (:inherit (variable-pitch) :height 1.2 :weight bold)) (((class color) (background dark)) (:foreground "pink")) (((min-colors 88) (class color) (background light)) (:foreground "red1")) (((class color) (background light)) (:foreground "red"))))
 '(custom-invalid ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#c60007" :background "#042028"))))
 '(custom-link ((t (:foreground "#5859b7" :inherit (link)))))
 '(custom-modified ((((min-colors 88) (class color)) (:background "blue1" :foreground "white")) (((class color)) (:background "blue" :foreground "white")) (t (:slant italic))))
 '(custom-rogue ((((class color)) (:background "black" :foreground "pink")) (t (:underline (:color foreground-color :style line)))))
 '(custom-saved ((t (:underline (:color foreground-color :style line)))))
 '(custom-set ((((min-colors 88) (class color)) (:background "white" :foreground "blue1")) (((class color)) (:background "white" :foreground "blue")) (t (:slant italic))))
 '(custom-state ((t (:foreground "#729a05"))))
 '(custom-tag ((t nil)))
 '(custom-variable-button ((t (:weight bold :underline (:color foreground-color :style line)))))
 '(custom-variable-tag ((t (:weight bold :foreground "#81908f"))))
 '(diary ((((min-colors 88) (class color) (background light)) (:foreground "red1")) (((class color) (background light)) (:foreground "red")) (((min-colors 88) (class color) (background dark)) (:foreground "yellow1")) (((class color) (background dark)) (:foreground "yellow")) (t (:weight bold))))
 '(dictionary-button ((t nil)))
 '(dictionary-reference ((t nil)))
 '(dictionary-word-entry ((t nil)))
 '(diff-added-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#729a05" :background "#335533" :inherit (diff-changed)))))
 '(diff-context-face ((t (:inherit (shadow)))))
 '(diff-file-header-face ((t (:weight bold :background "#042028"))))
 '(diff-header-face ((t (:foreground "#81908f" :background "#042028"))))
 '(diff-hunk-header-face ((t (:inherit (diff-header)))))
 '(diff-index-face ((t (:inherit (diff-file-header)))))
 '(diff-refine-added ((default (:inherit (diff-refine-change))) (((class color) (min-colors 88) (background light)) (:background "#aaffaa")) (((class color) (min-colors 88) (background dark)) (:background "#22aa22"))))
 '(diff-refine-change-face ((t nil)))
 '(diff-removed-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007" :background "#553333" :inherit (diff-changed)))))
 '(diredp-compressed-file-suffix ((t nil)))
 '(diredp-date-time ((t nil)))
 '(diredp-default ((t nil)))
 '(diredp-deletion ((t nil)))
 '(diredp-deletion-file-name ((t nil)))
 '(diredp-dir-heading ((t nil)))
 '(diredp-dir-priv ((t nil)))
 '(diredp-display-msg ((t nil)))
 '(diredp-exec-priv ((t nil)))
 '(diredp-executable-tag ((t nil)))
 '(diredp-file-name ((t nil)))
 '(diredp-file-suffix ((t nil)))
 '(diredp-flag-mark ((t nil)))
 '(diredp-flag-mark-line ((t nil)))
 '(diredp-ignored-file-name ((t nil)))
 '(diredp-link-priv ((t nil)))
 '(diredp-no-priv ((t nil)))
 '(diredp-number ((t nil)))
 '(diredp-other-priv ((t nil)))
 '(diredp-rare-priv ((t nil)))
 '(diredp-read-priv ((t nil)))
 '(diredp-symlink ((t nil)))
 '(diredp-write-priv ((t nil)))
 '(ediff-current-diff-A ((t nil)))
 '(ediff-current-diff-B ((t nil)))
 '(ediff-current-diff-C ((t nil)))
 '(ediff-old-diff-A ((t nil)))
 '(ediff-old-diff-B ((t nil)))
 '(ediff-old-diff-C ((t nil)))
 '(emms-pbi-current ((t nil)))
 '(emms-pbi-mark-marked ((t nil)))
 '(emms-pbi-song ((t nil)))
 '(erc-action-face ((t nil)))
 '(erc-bold-face ((t nil)))
 '(erc-current-nick-face ((t nil)))
 '(erc-dangerous-host-face ((t nil)))
 '(erc-default-face ((t nil)))
 '(erc-direct-msg-face ((t nil)))
 '(erc-error-face ((t nil)))
 '(erc-fool-face ((t nil)))
 '(erc-highlight-face ((t nil)))
 '(erc-input-face ((t (:foreground "#465a61"))))
 '(erc-keyword-face ((t (:weight bold :underline nil :inverse-video nil :foreground "#a57705"))))
 '(erc-my-nick-face ((t (:foreground "#2075c7"))))
 '(erc-nick-default-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(erc-nick-msg-face ((t nil)))
 '(erc-notice-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(erc-pal-face ((t nil)))
 '(erc-prompt-face ((t nil)))
 '(erc-timestamp-face ((t (:foreground "#465a61"))))
 '(erc-underline-face ((t nil)))
 '(eshell-ls-archive ((t (:foreground "#c61b6e"))))
 '(eshell-ls-backup ((t (:foreground "#a57705"))))
 '(eshell-ls-clutter ((t (:foreground "#9d4632"))))
 '(eshell-ls-directory ((t (:foreground "#2075c7"))))
 '(eshell-ls-executable ((t (:foreground "#729a05"))))
 '(eshell-ls-missing ((t (:foreground "#c60007"))))
 '(eshell-ls-product ((t (:foreground "#a57705"))))
 '(eshell-ls-special ((t (:foreground "#5859b7"))))
 '(eshell-ls-symlink ((t (:foreground "#259185"))))
 '(eshell-ls-unreadable ((t (:foreground "#52676f"))))
 '(eshell-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#729a05"))))
 '(fancy-widget-button ((t nil)))
 '(fancy-widget-button-highlight ((t nil)))
 '(fancy-widget-button-pressed ((t nil)))
 '(fancy-widget-button-pressed-highlight ((t nil)))
 '(fancy-widget-documentation ((t nil)))
 '(fancy-widget-field ((t nil)))
 '(fancy-widget-inactive ((t nil)))
 '(fancy-widget-single-line-field ((t nil)))
 '(flyspell-duplicate ((t (:foreground "#a57705"))))
 '(flyspell-incorrect ((t (:foreground "#c60007"))))
 '(font-latex-bold ((t nil)))
 '(font-latex-sedate ((t nil)))
 '(font-latex-title-4 ((t nil)))
 '(font-latex-warning ((t nil)))
 '(font-lock-builtin-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#729a05"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground nil :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "DarkSeaGreen4"))))
 '(font-lock-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(font-lock-doc-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "DarkSeaGreen4" :inherit (font-lock-string-face)))))
 '(font-lock-doc-string-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "PaleGreen4"))))
 '(font-lock-function-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(font-lock-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#729a05"))))
 '(font-lock-negation-char-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#9d4632" :inherit (font-lock-builtin-face)))))
 '(font-lock-pseudo-keyword-face ((t nil)))
 '(font-lock-string-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185"))))
 '(font-lock-type-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#a57705"))))
 '(font-lock-variable-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(font-lock-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007" :inherit (error)))))
 '(gnus-cite-1-face ((t nil)))
 '(gnus-cite-10-face ((t nil)))
 '(gnus-cite-11-face ((t nil)))
 '(gnus-cite-2-face ((t nil)))
 '(gnus-cite-3-face ((t nil)))
 '(gnus-cite-4-face ((t nil)))
 '(gnus-cite-5-face ((t nil)))
 '(gnus-cite-6-face ((t nil)))
 '(gnus-cite-7-face ((t nil)))
 '(gnus-cite-8-face ((t nil)))
 '(gnus-cite-9-face ((t nil)))
 '(gnus-group-mail-1-empty-face ((t nil)))
 '(gnus-group-mail-1-face ((t nil)))
 '(gnus-group-mail-2-empty-face ((t nil)))
 '(gnus-group-mail-2-face ((t nil)))
 '(gnus-group-mail-3-empty-face ((t nil)))
 '(gnus-group-mail-3-face ((t nil)))
 '(gnus-group-mail-4-empty-face ((t nil)))
 '(gnus-group-mail-4-face ((t nil)))
 '(gnus-group-mail-5-empty-face ((t nil)))
 '(gnus-group-mail-5-face ((t nil)))
 '(gnus-group-mail-6-empty-face ((t nil)))
 '(gnus-group-mail-6-face ((t nil)))
 '(gnus-group-mail-low-empty-face ((t nil)))
 '(gnus-group-mail-low-face ((t nil)))
 '(gnus-group-news-1-empty-face ((t nil)))
 '(gnus-group-news-1-face ((t nil)))
 '(gnus-group-news-2-empty-face ((t nil)))
 '(gnus-group-news-2-face ((t nil)))
 '(gnus-group-news-3-empty-face ((t nil)))
 '(gnus-group-news-3-face ((t nil)))
 '(gnus-group-news-4-empty-face ((t nil)))
 '(gnus-group-news-4-face ((t nil)))
 '(gnus-group-news-5-empty-face ((t nil)))
 '(gnus-group-news-5-face ((t nil)))
 '(gnus-group-news-6-empty-face ((t nil)))
 '(gnus-group-news-6-face ((t nil)))
 '(gnus-group-news-low-empty-face ((t nil)))
 '(gnus-group-news-low-face ((t nil)))
 '(gnus-header-content-face ((t nil)))
 '(gnus-header-from-face ((t nil)))
 '(gnus-header-name-face ((t nil)))
 '(gnus-header-newsgroups-face ((t nil)))
 '(gnus-header-subject-face ((t nil)))
 '(gnus-signature-face ((t nil)))
 '(gnus-summary-cancelled-face ((t nil)))
 '(gnus-summary-high-ancient-face ((t nil)))
 '(gnus-summary-high-read-face ((t nil)))
 '(gnus-summary-high-ticked-face ((t nil)))
 '(gnus-summary-high-unread-face ((t nil)))
 '(gnus-summary-low-ancient-face ((t nil)))
 '(gnus-summary-low-read-face ((t nil)))
 '(gnus-summary-low-ticked-face ((t nil)))
 '(gnus-summary-low-unread-face ((t nil)))
 '(gnus-summary-normal-ancient-face ((t nil)))
 '(gnus-summary-normal-read-face ((t nil)))
 '(gnus-summary-normal-ticked-face ((t nil)))
 '(gnus-summary-normal-unread-face ((t nil)))
 '(gnus-summary-selected-face ((t nil)))
 '(gnus-x-face ((t nil)))
 '(helm-ff-directory ((t (:background "LightGray" :foreground "DarkRed"))))
 '(helm-ff-executable ((t (:foreground "green"))))
 '(helm-ff-file ((t (:inherit (font-lock-builtin-face)))))
 '(helm-grep-file ((t (:underline (:color foreground-color :style line) :foreground "BlueViolet"))))
 '(helm-grep-match ((t (:inherit (match)))))
 '(helm-header ((t (:inherit (header-line)))))
 '(helm-match ((t (:inherit (match)))))
 '(helm-selection ((((background dark)) (:underline (:color foreground-color :style line)  :background "#3b3518"))
				   (((background light)) (:underline (:color foreground-color :style line) :background "#b5ffd1"))))
 '(helm-selection-line ((t (:underline (:color foreground-color :style line) :background "IndianRed4"))))
 '(helm-source-header ((((background dark)) (:family "Sans Serif" :height 1.3 :weight bold :foreground "gray70" :background nil))
					   (((background light)) (:family "Sans Serif" :height 1.3 :weight bold :foreground "black" :background nil))))
 '(helm-visible-mark ((((min-colors 88) (background dark)) (:foreground "black" :background "green1")) (((background dark)) (:foreground "black" :background "green")) (((background light)) (:background "#d1f5ea")) (((min-colors 88)) (:background "green1")) (t (:background "green"))))
 '(help-argument-name ((t (:inherit (italic)))))
 '(hi-blue ((((background dark)) (:foreground "black" :background "light blue")) (t (:background "light blue"))))
 '(hi-green ((((min-colors 88) (background dark)) (:foreground "black" :background "green1")) (((background dark)) (:foreground "black" :background "green")) (((min-colors 88)) (:background "green1")) (t (:background "green"))))
 '(hi-pink ((((background dark)) (:foreground "black" :background "pink")) (t (:background "pink"))))
 '(hi-yellow ((((min-colors 88) (background dark)) (:foreground "black" :background "yellow1")) (((background dark)) (:foreground "black" :background "yellow")) (((min-colors 88)) (:background "yellow1")) (t (:background "yellow"))))
 '(highlight-current-line ((t nil)))
 '(hl-line ((t (:underline nil :background "#0a2832"))))
 '(holiday ((((class color) (background light)) (:background "pink")) (((class color) (background dark)) (:background "chocolate4")) (t (:inverse-video t))))
 '(ibuffer-deletion ((t nil)))
 '(ibuffer-help-buffer ((t nil)))
 '(ibuffer-marked ((t nil)))
 '(ibuffer-special-buffer ((t nil)))
 '(icompletep-choices ((t nil)))
 '(icompletep-determined ((t nil)))
 '(icompletep-keys ((t nil)))
 '(icompletep-nb-candidates ((t nil)))
 '(ido-first-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#729a05"))))
 '(ido-only-match ((t (:foreground "#729a05"))))
 '(ido-subdir ((t (:foreground "#2075c7"))))
 '(iedit-occurrence ((t (:inherit (isearch)))))
 '(imaxima-latex-error ((t nil)))
 '(info-header-node ((t nil)))
 '(info-header-xref ((t nil)))
 '(info-menu-5 ((t nil)))
 '(info-menu-header ((t nil)))
 '(info-menu-star ((t nil)))
 '(info-node ((t nil)))
 '(info-title-4 ((t nil)))
 '(info-xref ((t (:weight normal :slant normal :underline (:color foreground-color :style line) :inverse-video nil :foreground "#2075c7"))))
 '(info-xref-visited ((t (:foreground "#c61b6e" :inherit (info-xref)))))
 '(isearch ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#9d4632" :background "#042028"))))
 '(isearch-fail ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#9d4632" :background "#042028"))))
 '(jabber-chat-prompt-foreign ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007"))))
 '(jabber-chat-prompt-local ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(jabber-rare-time-face ((t nil)))
 '(jabber-roster-user-away ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#729a05"))))
 '(jabber-roster-user-chatty ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#9d4632"))))
 '(jabber-roster-user-dnd ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#c60007"))))
 '(jabber-roster-user-error ((t (:weight light :slant italic :foreground "#c60007"))))
 '(jabber-roster-user-offline ((t (:foreground "#465a61"))))
 '(jabber-roster-user-online ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(jabber-roster-user-xa ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#c61b6e"))))
 '(jabber-title-large ((t nil)))
 '(jabber-title-medium ((t nil)))
 '(jabber-title-small ((t nil)))
 '(jde-java-font-lock-constant-face ((t nil)))
 '(jde-java-font-lock-doc-tag-face ((t nil)))
 '(jde-java-font-lock-link-face ((t nil)))
 '(jde-java-font-lock-modifier-face ((t nil)))
 '(jde-java-font-lock-number-face ((t nil)))
 '(jde-java-font-lock-operator-face ((t nil)))
 '(jde-java-font-lock-package-face ((t nil)))
 '(keywiz-command-face ((t (:inherit (quote variable-pitch) :height 1.2 :weight bold :foreground "Blue"))))
 '(keywiz-right-face ((t (:foreground "dark green"))))
 '(keywiz-wrong-face ((t (:foreground "Red"))))
 '(lazy-highlight ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#a57705" :background "#042028"))))
 '(magit-branch ((t (:inherit (magit-header)))))
 '(magit-item-highlight ((t (:inherit (highlight)))))
 '(magit-section-title ((t (:inherit (magit-header)))))
 '(makefile-shell ((t nil)))
 '(makefile-space ((t nil)))
 '(message-cited-text-face ((t nil)))
 '(message-header-cc-face ((t nil)))
 '(message-header-from-face ((t nil)))
 '(message-header-name-face ((t nil)))
 '(message-header-newsgroups-face ((t nil)))
 '(message-header-other-face ((t nil)))
 '(message-header-subject-face ((t nil)))
 '(message-header-to-face ((t nil)))
 '(message-header-xheader-face ((t nil)))
 '(message-mml-face ((t nil)))
 '(message-separator-face ((t nil)))
 '(minimap-active-region-background ((t nil)))
 '(mm/master-face ((t nil)))
 '(mm/mirror-face ((t nil)))
 '(org-agenda-clocking ((t nil)))
 '(org-agenda-date ((t nil)))
 '(org-agenda-date-today ((t nil)))
 '(org-agenda-date-weekend ((t nil)))
 '(org-agenda-structure ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8)) (:bold t :foreground "blue")) (t (:bold t))))
 '(org-archived ((t (:inherit (shadow)))))
 '(org-checkbox ((t (:inherit (bold)))))
 '(org-date ((((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "Purple")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "Cyan")) (t (:underline (:color foreground-color :style line)))))
 '(org-deadline-announce ((t nil)))
 '(org-document-title ((((class color) (background light)) (:weight bold :foreground "midnight blue")) (((class color) (background dark)) (:weight bold :foreground "pale turquoise")) (t (:weight bold))))
 '(org-done ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#729a05"))))
 '(org-formula ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:foreground "red")) (t (:italic t :bold t))))
 '(org-headline-done ((((class color) (min-colors 16) (background light)) (:foreground "RosyBrown")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSalmon")) (((class color) (min-colors 8) (background light)) (:bold nil))))
 '(org-hide ((t (:foreground "#042028"))))
 '(org-level-1 ((t (:inherit (outline-1)))))
 '(org-level-2 ((t (:inherit (outline-2)))))
 '(org-level-3 ((t (:inherit (outline-3)))))
 '(org-level-4 ((t (:inherit (outline-4)))))
 '(org-level-5 ((t (:inherit (outline-5)))))
 '(org-level-6 ((t (:inherit (outline-6)))))
 '(org-level-7 ((t (:inherit (outline-7)))))
 '(org-level-8 ((t (:inherit (outline-8)))))
 '(org-link ((t (:inherit (link)))))
 '(org-scheduled ((((class color) (min-colors 88) (background light)) (:foreground "DarkGreen")) (((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:italic t :bold t))))
 '(org-scheduled-previously ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:bold t :foreground "red")) (t (:bold t))))
 '(org-scheduled-today ((((class color) (min-colors 88) (background light)) (:foreground "DarkGreen")) (((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:italic t :bold t))))
 '(org-special-keyword ((t (:inherit (font-lock-keyword-face)))))
 '(org-table ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8) (background light)) (:foreground "blue")) (((class color) (min-colors 8) (background dark)) nil)))
 '(org-tag ((t (:bold t))))
 '(org-time-grid ((((class color) (min-colors 16) (background light)) (:foreground "DarkGoldenrod")) (((class color) (min-colors 16) (background dark)) (:foreground "LightGoldenrod")) (((class color) (min-colors 8)) (:weight light :foreground "yellow"))))
 '(org-todo ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#042028" :background "#c60007"))))
 '(org-upcoming-deadline ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:bold t :foreground "red")) (t (:bold t))))
 '(org-warning ((t (:inherit (font-lock-warning-face)))))
 '(outline-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7" :inherit (font-lock-function-name-face)))))
 '(outline-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#259185" :inherit (font-lock-variable-name-face)))))
 '(outline-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#a57705" :inherit (font-lock-keyword-face)))))
 '(outline-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#c60007" :inherit (font-lock-comment-face)))))
 '(outline-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#708183" :inherit (font-lock-type-face)))))
 '(outline-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#465a61" :inherit (font-lock-constant-face)))))
 '(outline-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#9d4632" :inherit (font-lock-builtin-face)))))
 '(outline-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5859b7" :inherit (font-lock-string-face)))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#259185"))))
 '(rainbow-delimiters-depth-10-face ((t nil)))
 '(rainbow-delimiters-depth-11-face ((t nil)))
 '(rainbow-delimiters-depth-12-face ((t nil)))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#a57705"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#2075c7"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#c60007"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#729a05"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#2075c7"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#9d4632"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#c61b6e"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#708183"))))
 '(rcirc-bright-nick ((t (:foreground "#c61b6e"))))
 '(rcirc-dim-nick ((t nil)))
 '(rcirc-mode-line-nick ((t nil)))
 '(rcirc-my-nick ((t (:foreground "#2075c7"))))
 '(rcirc-nick-in-message ((t (:foreground "#9d4632"))))
 '(rcirc-other-nick ((t (:foreground "#729a05"))))
 '(rcirc-prompt ((t (:foreground "#a57705"))))
 '(rcirc-server ((t (:foreground "#81908f"))))
 '(rcirc-server-prefix ((t nil)))
 '(rcirc-timestamp ((t (:foreground "#465a61"))))
 '(rst-level-1-face ((t nil)))
 '(rst-level-2-face ((t nil)))
 '(rst-level-3-face ((t nil)))
 '(rst-level-4-face ((t nil)))
 '(setnu-line-number ((t nil)))
 '(show-paren-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#259185" :background "#0a2832"))))
 '(show-paren-mismatch ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#c60007" :background "#465a61"))))
 '(speedbar-button-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#81908f"))))
 '(speedbar-directory-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#9d4632"))))
 '(speedbar-file-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#729a05"))))
 '(speedbar-highlight-face ((t (:background "#0a2832"))))
 '(speedbar-tag-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2075c7"))))
 '(strokes-char-face ((t nil)))
 '(todoo-item-assigned-header-face ((t nil)))
 '(todoo-item-header-face ((t nil)))
 '(todoo-sub-item-header-face ((t nil)))
 '(tuareg-font-lock-governing-face ((t nil)))
 '(tuareg-font-lock-interactive-error-face ((t nil)))
 '(tuareg-font-lock-interactive-output-face ((t nil)))
 '(tuareg-font-lock-operator-face ((t nil)))
 '(twittering-uri-face ((t nil)))
 '(twittering-username-face ((t nil)))
 '(w3m-anchor-face ((t nil)))
 '(w3m-arrived-anchor-face ((t nil)))
 '(w3m-form-button-face ((t nil)))
 '(w3m-form-button-mouse-face ((t nil)))
 '(w3m-form-button-pressed-face ((t nil)))
 '(w3m-form-face ((t nil)))
 '(w3m-image-face ((t nil)))
 '(w3m-tab-background-face ((t nil)))
 '(w3m-tab-selected-face ((t nil)))
 '(w3m-tab-selected-retrieving-face ((t nil)))
 '(w3m-tab-unselected-face ((t nil)))
 '(w3m-tab-unselected-retrieving-face ((t nil)))
 '(wg-brace-face ((t nil)))
 '(wg-command-face ((t nil)))
 '(wg-current-workgroup-face ((t nil)))
 '(wg-divider-face ((t nil)))
 '(wg-filename-face ((t nil)))
 '(wg-frame-face ((t nil)))
 '(wg-message-face ((t nil)))
 '(wg-mode-line-face ((t nil)))
 '(wg-other-workgroup-face ((t nil)))
 '(wg-previous-workgroup-face ((t nil)))
 '(wgrep-delete-face ((((class color) (background dark)) (:foreground "pink" :background "SlateGray1")) (((class color) (background light)) (:foreground "pink" :background "ForestGreen")) (t nil)))
 '(wgrep-face ((((class color) (background dark)) (:foreground "Black" :background "SlateGray1")) (((class color) (background light)) (:foreground "white" :background "ForestGreen")) (t nil)))
 '(which-func ((((class color) (min-colors 88) (background light)) (:inherit (font-lock-function-name-face)))
			   (((class grayscale mono) (background dark)) (:inherit (font-lock-function-name-face)))
			   (((class color) (background light)) (:inherit (font-lock-function-name-face)))
			   (((class color) (min-colors 88) (background dark)) (:foreground "SeaGreen3"))
			   (((background dark)) (:foreground "Blue4"))
			   (t (:foreground "LightSkyBlue"))))
 '(wl-highlight-folder-few-face ((t nil)))
 '(wl-highlight-folder-many-face ((t nil)))
 '(wl-highlight-folder-path-face ((t nil)))
 '(wl-highlight-folder-unknown-face ((t nil)))
 '(wl-highlight-folder-unread-face ((t nil)))
 '(wl-highlight-folder-zero-face ((t nil)))
 '(wl-highlight-message-citation-header ((t nil)))
 '(wl-highlight-message-cited-text-1 ((t nil)))
 '(wl-highlight-message-cited-text-2 ((t nil)))
 '(wl-highlight-message-cited-text-3 ((t nil)))
 '(wl-highlight-message-cited-text-4 ((t nil)))
 '(wl-highlight-message-header-contents ((t nil)))
 '(wl-highlight-message-header-contents-face ((t nil)))
 '(wl-highlight-message-headers-face ((t nil)))
 '(wl-highlight-message-important-header-contents ((t nil)))
 '(wl-highlight-message-important-header-contents2 ((t nil)))
 '(wl-highlight-message-signature ((t nil)))
 '(wl-highlight-message-unimportant-header-contents ((t nil)))
 '(wl-highlight-summary-answered-face ((t nil)))
 '(wl-highlight-summary-displaying-face ((t nil)))
 '(wl-highlight-summary-disposed-face ((t nil)))
 '(wl-highlight-summary-new-face ((t nil)))
 '(wl-highlight-summary-normal-face ((t nil)))
 '(wl-highlight-summary-refiled-face ((t nil)))
 '(wl-highlight-summary-thread-top-face ((t nil)))
 '(wl-highlight-thread-indent-face ((t nil))))

(provide-theme 'my-solarized-dark)
