(deftheme my-zenburn
  "my dark theme for coding")

(custom-theme-set-faces
 'my-zenburn
 `(default
	((t (		 :family ,my-default-font-name
				 ;; :foundry "apple"
				 :width normal
				 :height ,(* 10 my-default-font-size)
				 :weight normal
				 :slant normal
				 :underline nil
				 :overline nil
				 :strike-through nil
				 :box nil
				 :inverse-video nil
				 :foreground "#dcdccc"
				 :background "#2f3030"
				 :stipple nil
				 :inherit nil))))
 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:weight bold :slant italic))))
 '(fixed-pitch ((t (:weight bold))))
 '(italic ((t (:slant italic))))
 '(underline ((t (:underline (:color foreground-color :style line)))))
 '(variable-pitch ((t (:inherit (default) :family "³ª´®°íµñ" :weight bold))))
 '(fringe ((t (:background "#303030" :inherit (default)))))
 '(header-line ((t (:box (:line-width 2 :color "#2e3330" :style nil) :inherit (zenburn-highlight-damp)))))
 '(highlight ((t (:weight bold :underline nil :foreground "#2a2a2a" :background "#2c888b" :inherit (zenburn-highlight-subtle)))))
 '(hover-highlight ((t (:foreground "#f0dfaf" :underline (:color foreground-color :style line)))))
 '(match ((t (:underline nil :inherit (zenburn-highlight-alerting)))))
 '(menu ((t (:background "#1e2320"))))
 '(mouse ((t (:inherit (zenburn-foreground)))))
 '(paren ((t (:inherit (zenburn-red)))))
 '(trailing-whitespace ((t (:background "#2f2520" :inherit (font-lock-warning-face)))))
 '(buffer-menu-buffer ((t (:inherit (zenburn-primary-1)))))
 '(border ((t (:background "#1f1f1f"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#d0bf8f"))))
 '(cursor ((t (:background "#aaaaaa"))))
 '(escape-glyph-face ((t (:foreground "#cc9393"))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#bd950c"))))
 '(minibuffer-prompt ((t (:foreground "#f0dfaf"))))
 '(mode-line ((t (:height 1.0 :foreground "#000000" :background "#Daa520" :inverse-video nil))))
 '(mode-line-inactive ((t (:inherit (mode-line) :foreground "#303030" :background "#8b6508"))))
 '(mode-line-buffer-id ((t (:weight bold :slant italic))))
 '(mode-line-emphasis ((t (:inherit (mode-line) :weight bold :weight bold))))
 '(mode-line-highlight ((t (:inherit (mode-line-emphasis)))))
 '(region ((t (:background "#5f5f5f"))))
 '(scroll-bar ((t (:background "#5f5f5f"))))
 '(secondary-selection ((t (:background "#5f5f5f"))))
 '(tool-bar ((t (:background "#5f5f5f"))))
 '(apt-utils-broken ((t (:inherit (font-lock-warning-face)))))
 '(apt-utils-description ((t (:inherit (default)))))
 '(apt-utils-field-contents ((t (:inherit (font-lock-comment-face)))))
 '(apt-utils-field-keyword ((t (:inherit (font-lock-doc-face)))))
 '(apt-utils-normal-package ((t (:inherit (zenburn-primary-1)))))
 '(apt-utils-summary ((t (:inherit (bold)))))
 '(apt-utils-version ((t (:inherit (zenburn-blue)))))
 '(apt-utils-virtual-package ((t (:inherit (zenburn-primary-2)))))
 '(breakpoint-disabled-bitmap ((t (:inherit (font-lock-comment-face)))))
 '(breakpoint-enabled-bitmap ((t (:inherit (zenburn-primary-1)))))
 '(calendar-today ((t (:inherit (zenburn-primary-2) :underline nil))))
 '(change-log-date ((t (:inherit (zenburn-blue)))))
 '(circe-highlight-nick-face ((t (:inherit (zenburn-primary-1)))))
 '(circe-my-message-face ((t (:inherit (zenburn-yellow)))))
 '(circe-originator-face ((t (:inherit (bold)))))
 '(circe-prompt-face ((t (:inherit (zenburn-primary-1)))))
 '(circe-server-face ((t (:inherit (font-lock-comment-face)))))
 '(comint-highlight-input ((t (:inherit (zenburn-primary-1)))))
 '(comint-highlight-prompt ((t (:inherit (zenburn-primary-2)))))
 '(compilation-info ((t (:inherit (zenburn-primary-1)))))
 '(compilation-warning ((t (:inherit (font-lock-warning-face)))))
 '(cscope-line-face ((t (:inherit (my-dark-green+1)))))
 '(cua-rectangle ((t (:inherit (region)))))
 '(custom-button ((t (:inherit (fancy-widget-button)))))
 '(custom-button-pressed ((t (:inherit (fancy-widget-button-pressed)))))
 '(custom-changed ((t (:inherit (zenburn-blue)))))
 '(custom-comment ((t (:inherit (font-lock-doc-face)))))
 '(custom-comment-tag ((t (:inherit (font-lock-doc-face)))))
 '(custom-documentation ((t (:inherit (font-lock-doc-face)))))
 '(custom-group-tag ((t (:inherit (zenburn-primary-1)))))
 '(custom-group-tag-1 ((t (:inherit (zenburn-primary-4)))))
 '(custom-invalid ((t (:inherit (font-lock-warning-face)))))
 '(custom-link ((t (:underline (:color foreground-color :style line) :inherit (zenburn-yellow)))))
 '(custom-modified ((t (:inherit (zenburn-primary-3)))))
 '(custom-rogue ((t (:inherit (font-lock-warning-face)))))
 '(custom-saved ((t (:underline (:color foreground-color :style line)))))
 '(custom-set ((t (:inherit (zenburn-blue) :inverse-video t))))
 '(custom-state ((t (:inherit (font-lock-comment-face)))))
 '(custom-tag ((t (:inherit (zenburn-primary-2)))))
 '(custom-variable-button ((t (:underline (:color foreground-color :style line) :weight bold))))
 '(custom-variable-tag ((t (:inherit (zenburn-primary-2)))))
 '(diary ((t (:inherit (zenburn-primary-1) :underline nil))))
 '(dictionary-button ((t (:inherit (fancy-widget-button)))))
 '(dictionary-reference ((t (:inherit (zenburn-primary-1)))))
 '(dictionary-word-entry ((t (:inherit (font-lock-keyword-face)))))
 '(diff-added-face ((t (:inherit (zenburn-primary-3)))))
 '(diff-context-face ((t (:inherit (font-lock-comment-face)))))
 '(diff-file-header-face ((t (:inherit (bold)))))
 '(diff-header-face ((t (:inherit (zenburn-highlight-subtle)))))
 '(diff-hunk-header-face ((t (:inherit (zenburn-highlight-subtle)))))
 '(diff-index-face ((t (:inherit (bold)))))
 '(diff-refine-added ((t (:background "#698b69" :inherit (diff-refine-change)))))
 '(diff-refine-change-face ((t (:inherit (zenburn-background-2)))))
 '(diff-removed-face ((t (:inherit (zenburn-blue)))))
 '(diredp-compressed-file-suffix ((t (:foreground "#2c888b" :inherit (diredp-default)))))
 '(diredp-date-time ((t (:foreground "#4cb8bb" :inherit (diredp-default)))))
 '(diredp-default ((t (:background "#2a2a2a" :inherit (default)))))
 '(diredp-deletion ((t (:foreground "#2a2a2a" :background "#Ff7f24" :inherit (diredp-default)))))
 '(diredp-deletion-file-name ((t (:foreground "#Ff7f24" :inherit (diredp-default)))))
 '(diredp-dir-heading ((t (:slant italic :foreground "#df790f" :inherit (diredp-default)))))
 '(diredp-dir-priv ((t (:slant italic :foreground "#4cb8bb" :background "#2a2a2a" :inherit (diredp-default)))))
 '(diredp-display-msg ((t (:foreground "#df790f" :inherit (diredp-default)))))
 '(diredp-exec-priv ((t (:foreground "#bd950c" :background "#2a2a2a" :inherit (diredp-default)))))
 '(diredp-executable-tag ((t (:foreground "#Ff7f24" :inherit (diredp-default)))))
 '(diredp-file-name ((t (:foreground "#df790f" :inherit (diredp-default)))))
 '(diredp-file-suffix ((t (:slant italic :foreground "#dcdccc" :inherit (diredp-default)))))
 '(diredp-flag-mark ((t (:foreground "#2e8b57" :background "#2a2a2a" :inherit (diredp-default)))))
 '(diredp-flag-mark-line ((t (:foreground "black" :background "#8b6508" :inherit (diredp-default)))))
 '(diredp-ignored-file-name ((t (:foreground "#505050" :inherit (diredp-default)))))
 '(diredp-link-priv ((t (:foreground "#5cd0d3" :background "#2a2a2a" :inherit (diredp-default)))))
 '(diredp-no-priv ((t (:foreground "#dcdccc" :background "#2a2a2a" :inherit (diredp-default)))))
 '(diredp-number ((t (:foreground "#dcdccc" :inherit (diredp-default)))))
 '(diredp-other-priv ((t (:foreground "#3ca0a3" :background "#2a2a2a" :inherit (diredp-default)))))
 '(diredp-rare-priv ((t (:foreground "#1c7073" :background "#2a2a2a" :inherit (diredp-default)))))
 '(diredp-read-priv ((t (:foreground "#2c888b" :background "#2a2a2a" :inherit (diredp-default)))))
 '(diredp-symlink ((t (:foreground "#4cb8bb" :inherit (diredp-default)))))
 '(diredp-write-priv ((t (:foreground "#9bcd9b" :background "#2a2a2a" :inherit (diredp-default)))))
 '(ediff-current-diff-A ((t (:foreground "#000000" :background "#Cd6600" :inherit (default)))))
 '(ediff-current-diff-B ((t (:foreground "#000000" :background "#Cd8500" :inherit (default)))))
 '(ediff-current-diff-C ((t (:foreground "#000000" :background "#8b4500" :inherit (default)))))
 '(ediff-old-diff-A ((t (:foreground "#000000" :background "#3ca0a3" :inherit (default)))))
 '(ediff-old-diff-B ((t (:foreground "#000000" :background "#2c888b" :inherit (default)))))
 '(ediff-old-diff-C ((t (:foreground "#000000" :background "#1c7073" :inherit (default)))))
 '(emms-pbi-current ((t (:inherit (zenburn-primary-1)))))
 '(emms-pbi-mark-marked ((t (:inherit (zenburn-primary-2)))))
 '(emms-pbi-song ((t (:foreground "#f0dfaf"))))
 '(erc-action-face ((t (:inherit (erc-default-face)))))
 '(erc-bold-face ((t (:weight bold))))
 '(erc-current-nick-face ((t (:inherit (zenburn-primary-1)))))
 '(erc-dangerous-host-face ((t (:inherit (font-lock-warning-face)))))
 '(erc-default-face ((t (:foreground "#dcdccc"))))
 '(erc-direct-msg-face ((t (:inherit (erc-default-face)))))
 '(erc-error-face ((t (:inherit (font-lock-warning-face)))))
 '(erc-fool-face ((t (:inherit (zenburn-lowlight-1)))))
 '(erc-highlight-face ((t (:inherit (hover-highlight)))))
 '(erc-input-face ((t (:foreground "#f0dfaf"))))
 '(erc-keyword-face ((t (:inherit (zenburn-primary-1)))))
 '(erc-my-nick-face ((t (:inherit (zenburn-red)))))
 '(erc-nick-default-face ((t (:inherit (bold)))))
 '(erc-nick-msg-face ((t (:inherit (erc-default-face)))))
 '(erc-notice-face ((t (:inherit (zenburn-green)))))
 '(erc-pal-face ((t (:inherit (zenburn-primary-3)))))
 '(erc-prompt-face ((t (:inherit (zenburn-primary-2)))))
 '(erc-timestamp-face ((t (:inherit (zenburn-green+1)))))
 '(erc-underline-face ((t (:inherit (underline)))))
 '(eshell-ls-archive ((t (:weight bold :foreground "#bc8383"))))
 '(eshell-ls-backup ((t (:inherit (font-lock-comment-face)))))
 '(eshell-ls-clutter ((t (:inherit (font-lock-comment-face)))))
 '(eshell-ls-directory ((t (:weight bold :foreground "#94bff3"))))
 '(eshell-ls-executable ((t (:weight bold :foreground "#dca3a3"))))
 '(eshell-ls-missing ((t (:inherit (font-lock-warning-face)))))
 '(eshell-ls-product ((t (:inherit (font-lock-doc-face)))))
 '(eshell-ls-special ((t (:inherit (zenburn-primary-1)))))
 '(eshell-ls-symlink ((t (:weight bold :foreground "#93e0e3"))))
 '(eshell-ls-unreadable ((t (:inherit (zenburn-lowlight-1)))))
 '(eshell-prompt ((t (:inherit (zenburn-primary-1)))))
 '(fancy-widget-button ((t (:box (:line-width 2 :color nil :style released-button) :background "#4f4f4f"))))
 '(fancy-widget-button-highlight ((t (:box (:line-width 2 :color nil :style released-button) :background "#4f4f4f"))))
 '(fancy-widget-button-pressed ((t (:box (:line-width 2 :color nil :style pressed-button) :background "#4f4f4f"))))
 '(fancy-widget-button-pressed-highlight ((t (:box (:line-width 2 :color nil :style pressed-button) :background "#4f4f4f"))))
 '(fancy-widget-documentation ((t (:inherit (font-lock-doc-face)))))
 '(fancy-widget-field ((t (:background "#5f5f5f"))))
 '(fancy-widget-inactive ((t (:strike-through t))))
 '(fancy-widget-single-line-field ((t (:background "#5f5f5f"))))
 '(flyspell-duplicate ((t (:weight bold :foreground "#f0dfaf"))))
 '(flyspell-incorrect ((t (:weight bold :foreground "#cc9393"))))
 '(font-latex-bold ((t (:inherit (bold)))))
 '(font-latex-sedate ((t (:inherit (zenburn-primary-1)))))
 '(font-latex-title-4 ((t (:inherit (zenburn-title)))))
 '(font-latex-warning ((t (:inherit (font-lock-warning-face)))))
 '(font-lock-builtin-face ((t (:inherit (zenburn-blue)))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7f9f7f" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#7f9f7f"))))
 '(font-lock-constant-face ((t (:inherit (zenburn-primary-4)))))
 '(font-lock-doc-face ((t (:inherit (zenburn-green+1)))))
 '(font-lock-doc-string-face ((t (:foreground "#94bff3"))))
 '(font-lock-function-name-face ((t (:foreground "#8cd0d3"))))
 '(font-lock-keyword-face ((t (:slant italic :inherit (zenburn-primary-1)))))
 '(font-lock-negation-char-face ((t (:inherit (zenburn-primary-1)))))
 '(font-lock-operator-face ((t (:inherit (zenburn-primary-3)))))
 '(font-lock-preprocessor-face ((t (:inherit (zenburn-red)))))
 '(font-lock-pseudo-keyword-face ((t (:inherit (zenburn-primary-2)))))
 '(font-lock-string-face ((t (:inherit (zenburn-red-2)))))
 '(font-lock-type-face ((t (:inherit (zenburn-primary-3)))))
 '(font-lock-variable-name-face ((t (:foreground "#f0dfaf"))))
 '(font-lock-warning-face ((t (:inherit (zenburn-highlight-alerting)))))
 '(gnus-cite-1-face ((t (:foreground "#8cd0d3"))))
 '(gnus-cite-10-face ((t (:foreground "#e0cf9f"))))
 '(gnus-cite-11-face ((t (:foreground "#f0dfaf"))))
 '(gnus-cite-2-face ((t (:foreground "#7cb8bb"))))
 '(gnus-cite-3-face ((t (:foreground "#6ca0a3"))))
 '(gnus-cite-4-face ((t (:foreground "#9fc59f"))))
 '(gnus-cite-5-face ((t (:foreground "#8fb28f"))))
 '(gnus-cite-6-face ((t (:foreground "#7f9f7f"))))
 '(gnus-cite-7-face ((t (:foreground "#cc9393"))))
 '(gnus-cite-8-face ((t (:foreground "#bc8383"))))
 '(gnus-cite-9-face ((t (:foreground "#ac7373"))))
 '(gnus-group-mail-1-empty-face ((t (:inherit (gnus-group-news-1-empty-face)))))
 '(gnus-group-mail-1-face ((t (:inherit (gnus-group-mail-1-empty-face) :weight bold))))
 '(gnus-group-mail-2-empty-face ((t (:inherit (gnus-group-news-2-empty-face)))))
 '(gnus-group-mail-2-face ((t (:inherit (gnus-group-mail-2-empty-face) :weight bold))))
 '(gnus-group-mail-3-empty-face ((t (:inherit (gnus-group-news-3-empty-face)))))
 '(gnus-group-mail-3-face ((t (:inherit (gnus-group-mail-3-empty-face) :weight bold))))
 '(gnus-group-mail-4-empty-face ((t (:inherit (gnus-group-news-4-empty-face)))))
 '(gnus-group-mail-4-face ((t (:inherit (gnus-group-mail-4-empty-face) :weight bold))))
 '(gnus-group-mail-5-empty-face ((t (:inherit (gnus-group-news-5-empty-face)))))
 '(gnus-group-mail-5-face ((t (:inherit (gnus-group-mail-5-empty-face) :weight bold))))
 '(gnus-group-mail-6-empty-face ((t (:inherit (gnus-group-news-6-empty-face)))))
 '(gnus-group-mail-6-face ((t (:inherit (gnus-group-mail-6-empty-face) :weight bold))))
 '(gnus-group-mail-low-empty-face ((t (:inherit (gnus-group-news-low-empty-face)))))
 '(gnus-group-mail-low-face ((t (:inherit (gnus-group-mail-low-empty-face) :weight bold))))
 '(gnus-group-news-1-empty-face ((t (:foreground "#f0dfaf"))))
 '(gnus-group-news-1-face ((t (:inherit (gnus-group-news-1-empty-face) :weight bold))))
 '(gnus-group-news-2-empty-face ((t (:foreground "#afd8af"))))
 '(gnus-group-news-2-face ((t (:inherit (gnus-group-news-2-empty-face) :weight bold))))
 '(gnus-group-news-3-empty-face ((t (:foreground "#8fb28f"))))
 '(gnus-group-news-3-face ((t (:inherit (gnus-group-news-3-empty-face) :weight bold))))
 '(gnus-group-news-4-empty-face ((t (:foreground "#6ca0a3"))))
 '(gnus-group-news-4-face ((t (:inherit (gnus-group-news-4-empty-face) :weight bold))))
 '(gnus-group-news-5-empty-face ((t (:foreground "#5c888b"))))
 '(gnus-group-news-5-face ((t (:inherit (gnus-group-news-5-empty-face) :weight bold))))
 '(gnus-group-news-6-empty-face ((t (:inherit (zenburn-lowlight-1)))))
 '(gnus-group-news-6-face ((t (:inherit (gnus-group-news-6-empty-face) :weight bold))))
 '(gnus-group-news-low-empty-face ((t (:inherit (zenburn-lowlight-1)))))
 '(gnus-group-news-low-face ((t (:inherit (gnus-group-news-low-empty-face) :weight bold))))
 '(gnus-header-content-face ((t (:inherit (message-header-other-face)))))
 '(gnus-header-from-face ((t (:inherit (message-header-from-face)))))
 '(gnus-header-name-face ((t (:inherit (message-header-name-face)))))
 '(gnus-header-newsgroups-face ((t (:inherit (message-header-other-face)))))
 '(gnus-header-subject-face ((t (:inherit (message-header-subject-face)))))
 '(gnus-signature-face ((t (:foreground "#f0dfaf"))))
 '(gnus-summary-cancelled-face ((t (:inherit (zenburn-highlight-alerting)))))
 '(gnus-summary-high-ancient-face ((t (:inherit (zenburn-blue)))))
 '(gnus-summary-high-read-face ((t (:weight bold :inherit (zenburn-green)))))
 '(gnus-summary-high-ticked-face ((t (:inherit (zenburn-primary-2)))))
 '(gnus-summary-high-unread-face ((t (:weight bold :inherit (zenburn-foreground)))))
 '(gnus-summary-low-ancient-face ((t (:weight normal :inherit (zenburn-blue)))))
 '(gnus-summary-low-read-face ((t (:weight normal :inherit (zenburn-green)))))
 '(gnus-summary-low-ticked-face ((t (:inherit (zenburn-primary-2)))))
 '(gnus-summary-low-unread-face ((t (:weight normal :inherit (zenburn-foreground)))))
 '(gnus-summary-normal-ancient-face ((t (:weight normal :inherit (zenburn-blue)))))
 '(gnus-summary-normal-read-face ((t (:weight normal :inherit (zenburn-green)))))
 '(gnus-summary-normal-ticked-face ((t (:inherit (zenburn-primary-2)))))
 '(gnus-summary-normal-unread-face ((t (:weight normal :inherit (zenburn-foreground)))))
 '(gnus-summary-selected-face ((t (:inherit (zenburn-primary-1)))))
 '(gnus-x-face ((t (:foreground "#1f1f1f" :background "#dcdccc"))))
 '(helm-ff-directory ((t (:inherit (italic)))))
 '(helm-ff-executable ((t (:foreground "#54ff9f" :inherit (italic)))))
 '(helm-ff-file ((t (:inherit (italic)))))
 '(helm-grep-file ((t (:underline (:color foreground-color :style line) :foreground "#bd950c"))))
 '(helm-grep-match ((t (:inherit (my-dark-red)))))
 '(helm-header ((t (:inherit (region)))))
 '(helm-match ((t (:foreground "#dfaf8f" :inherit (italic)))))
 '(helm-selection ((t (:weight bold :underline nil :inherit (region)))))
 '(helm-selection-line ((t (:underline (:color foreground-color :style line) :inherit (helm-selection)))))
 '(helm-source-header ((t (:family "Sans Serif" :height 1.3 :weight bold :underline nil :inherit (my-dark-highlight-damp)))))
 '(helm-visible-mark ((t (:foreground "black" :background "green1" :inherit (my-dark-highlight-subtle)))))
 '(help-argument-name ((t (:weight bold))))
 '(hi-blue ((t (:foreground "#366060"))))
 '(hi-green ((t (:foreground "#5f7f5f"))))
 '(hi-pink ((t (:foreground "#8c5353"))))
 '(hi-yellow ((t (:foreground "#f0dfaf"))))
 '(highlight-current-line ((t (:inherit (zenburn-highlight-subtle)))))
 '(hl-line ((t (:background "#303030" :inherit nil))))
 '(holiday ((t (:inherit (zenburn-primary-4) :underline (:color foreground-color :style line)))))
 '(ibuffer-deletion ((t (:inherit (zenburn-primary-2)))))
 '(ibuffer-help-buffer ((t (:inherit (font-lock-comment-face)))))
 '(ibuffer-marked ((t (:inherit (zenburn-primary-1)))))
 '(ibuffer-special-buffer ((t (:inherit (font-lock-doc-face)))))
 '(icompletep-choices ((t (:foreground "#dcdccc"))))
 '(icompletep-determined ((t (:foreground "#8fb28f"))))
 '(icompletep-keys ((t (:foreground "#cc9393"))))
 '(icompletep-nb-candidates ((t (:foreground "#afd8af"))))
 '(ido-first-match ((t (:inherit (zenburn-primary-1)))))
 '(ido-only-match ((t (:inherit (zenburn-primary-2)))))
 '(ido-subdir ((t (:foreground "#f0dfaf"))))
 '(imaxima-latex-error ((t (:inherit (font-lock-warning-face)))))
 '(info-header-node ((t (:weight normal))))
 '(info-header-xref ((t (:inherit (info-xref)))))
 '(info-menu-5 ((t (:inherit (info-menu-star)))))
 '(info-menu-header ((t (:foreground "#bd950c" :inherit (variable-pitch)))))
 '(info-menu-star ((t (:weight bold :foreground "#dfaf8f"))))
 '(info-node ((t (:weight bold))))
 '(info-title-4 ((t (:foreground "#df790f" :inherit (variable-pitch)))))
 '(info-xref ((t (:weight bold :foreground "#f0dfaf"))))
 '(info-xref-visited ((t (:weight normal :inherit (info-xref)))))
 '(isearch ((t (:background "#f0dfaf" :foreground "#1a0a0a"))))
 '(isearch-fail ((t (:background "#8c5353" :foreground "#dcdccc"))))
 '(jabber-chat-prompt-foreign ((t (:inherit (zenburn-primary-2)))))
 '(jabber-chat-prompt-local ((t (:inherit (zenburn-primary-1)))))
 '(jabber-rare-time-face ((t (:inherit (zenburn-green+1)))))
 '(jabber-roster-user-away ((t (:inherit (font-lock-doc-face)))))
 '(jabber-roster-user-chatty ((t (:inherit (zenburn-primary-1)))))
 '(jabber-roster-user-dnd ((t (:inherit (zenburn-primary-5)))))
 '(jabber-roster-user-error ((t (:inherit (font-lock-warning-face)))))
 '(jabber-roster-user-offline ((t (:inherit (zenburn-lowlight-1)))))
 '(jabber-roster-user-online ((t (:inherit (zenburn-primary-2)))))
 '(jabber-roster-user-xa ((t (:inherit (font-lock-comment-face)))))
 '(jabber-title-large ((t (:height 1.2 :inherit (jabber-title-medium)))))
 '(jabber-title-medium ((t (:height 1.2 :inherit (jabber-title-small)))))
 '(jabber-title-small ((t (:height 1.2 :inherit (zenburn-title)))))
 '(jde-java-font-lock-constant-face ((t (:inherit (font-lock-constant)))))
 '(jde-java-font-lock-doc-tag-face ((t (:inherit (zenburn-primary-1)))))
 '(jde-java-font-lock-link-face ((t (:underline (:color foreground-color :style line) :inherit (zenburn-primary-5)))))
 '(jde-java-font-lock-modifier-face ((t (:inherit (zenburn-primary-2)))))
 '(jde-java-font-lock-number-face ((t (:inherit (font-lock-constant)))))
 '(jde-java-font-lock-operator-face ((t (:inherit (font-lock-keyword-face)))))
 '(jde-java-font-lock-package-face ((t (:inherit (zenburn-primary-3)))))
 '(keywiz-command-face ((t (:inherit (zenburn-primary-2)))))
 '(keywiz-right-face ((t (:inherit (zenburn-primary-1)))))
 '(keywiz-wrong-face ((t (:inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:background "#5f5f5f" :foreground "#f0dfaf"))))
 '(magit-branch ((t (:inherit (zenburn-blue)))))
 '(magit-item-highlight ((t (:inherit (zenburn-blue)))))
 '(magit-section-title ((t (:inherit (zenburn-red)))))
 '(makefile-shell ((t (nil nil))))
 '(makefile-space ((t (:inherit (font-lock-warning-face)))))
 '(message-cited-text-face ((t (:inherit (font-lock-comment-face)))))
 '(message-header-cc-face ((t (:inherit (zenburn-primary-1)))))
 '(message-header-from-face ((t (:inherit (zenburn-primary-1)))))
 '(message-header-name-face ((t (:inherit (zenburn-green+1)))))
 '(message-header-newsgroups-face ((t (:inherit (zenburn-primary-1)))))
 '(message-header-other-face ((t (:inherit (zenburn-green)))))
 '(message-header-subject-face ((t (:inherit (zenburn-primary-2)))))
 '(message-header-to-face ((t (:inherit (zenburn-primary-1)))))
 '(message-header-xheader-face ((t (:inherit (zenburn-green)))))
 '(message-mml-face ((t (:inherit (zenburn-primary-1)))))
 '(message-separator-face ((t (:inherit (font-lock-comment-face)))))
 '(minimap-active-region-background ((t (:background "#233323"))))
 '(mm/master-face ((t (:inherit (region)))))
 '(mm/mirror-face ((t (:inherit (highlight)))))
 '(org-agenda-clocking ((t (:weight bold :background "#2e3330"))))
 '(org-agenda-date ((t (:foreground "#8cd0d3"))))
 '(org-agenda-date-today ((t (:weight bold :slant italic :foreground "#93e0e3"))))
 '(org-agenda-date-weekend ((t (:foreground "#94bff3"))))
 '(org-agenda-structure ((t (:inherit (font-lock-comment-face)))))
 '(org-archived ((t (:weight bold :foreground "#dcdccc"))))
 '(org-checkbox ((t (:box (:line-width 1 :color nil :style released-button) :foreground "white" :background "#5f5f5f"))))
 '(org-date ((t (:underline (:color foreground-color :style line) :foreground "#8cd0d3"))))
 '(org-deadline-announce ((t (:foreground "#bc8383"))))
 '(org-document-title ((t (:height 1.4 :weight bold :foreground "#00d0f3"))))
 '(org-done ((t (:foreground "#afd8af" :weight bold))))
 '(org-formula ((t (:foreground "#d0bf8f"))))
 '(org-headline-done ((t (:foreground "#afd8af"))))
 '(org-hide ((t (:foreground "#5f5f5f"))))
 '(org-level-1 ((t (:height 1.1 :foreground "#dfaf8f" :inherit (default)))))
 '(org-level-2 ((t (:height 1.0 :foreground "#f0dfaf" :inherit (org-level-1)))))
 '(org-level-3 ((t (:height 1.0 :foreground "#8cd0d3" :inherit (org-level-2)))))
 '(org-level-4 ((t (:height 1.0 :foreground "#93e0e3" :inherit (org-level-3)))))
 '(org-level-5 ((t (:foreground "#7cb8bb" :inherit (org-level-4)))))
 '(org-level-6 ((t (:foreground "#6ca0a3" :inherit (org-level-5)))))
 '(org-level-7 ((t (:foreground "#5c888b" :inherit (org-level-6)))))
 '(org-level-8 ((t (:foreground "#4c7073" :inherit (org-level-7)))))
 '(org-link ((t (:underline (:color foreground-color :style line) :foreground "#d0bf8f"))))
 '(org-scheduled ((t (:foreground "#bfebbf"))))
 '(org-scheduled-previously ((t (:foreground "#8c5353"))))
 '(org-scheduled-today ((t (:foreground "#94bff3"))))
 '(org-special-keyword ((t (:foreground "#e0cf9f"))))
 '(org-table ((t (:foreground "#9fc59f"))))
 '(org-tag ((t (:weight bold))))
 '(org-time-grid ((t (:foreground "#dfaf8f"))))
 '(org-todo ((t (:weight bold :foreground "#cc9393"))))
 '(org-upcoming-deadline ((t (:inherit (font-lock-keyword-face-face)))))
 '(org-warning ((t (:weight bold :foreground "#cc9393"))))
 '(outline-1 ((t (:height 1.0 :inherit (outline-2)))))
 '(outline-2 ((t (:height 1.0 :inherit (outline-3)))))
 '(outline-3 ((t (:height 1.0 :inherit (outline-4)))))
 '(outline-4 ((t (:height 1.0 :inherit (outline-5)))))
 '(outline-5 ((t (:height 1.0 :inherit (outline-6)))))
 '(outline-6 ((t (:height 1.0 :inherit (outline-7)))))
 '(outline-7 ((t (:height 1.0 :inherit (outline-8)))))
 '(outline-8 ((t (:inherit (default)))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#93e0e3"))))
 '(rainbow-delimiters-depth-10-face ((t (:foreground "#9fc59f"))))
 '(rainbow-delimiters-depth-11-face ((t (:foreground "#94bff3"))))
 '(rainbow-delimiters-depth-12-face ((t (:foreground "#8c5353"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#f0dfaf"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#94bff3"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#dca3a3"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#8fb28f"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#7cb8bb"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#dfaf8f"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#dc8cc3"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#d0bf8f"))))
 '(rcirc-bright-nick ((t (:inherit (rcirc-other-nick) :foreground "white"))))
 '(rcirc-dim-nick ((t (:inherit (font-lock-comment-face)))))
 '(rcirc-mode-line-nick ((t (:inherit (zenburn-primary-1)))))
 '(rcirc-my-nick ((t (:inherit (zenburn-primary-1)))))
 '(rcirc-nick-in-message ((t (:inherit (bold)))))
 '(rcirc-other-nick ((t (:inherit (bold)))))
 '(rcirc-prompt ((t (:inherit (zenburn-primary-1)))))
 '(rcirc-server ((t (:inherit (font-lock-comment-face)))))
 '(rcirc-server-prefix ((t (:inherit (font-lock-comment-face-delimiter)))))
 '(rcirc-timestamp ((t (:inherit (font-lock-comment-face)))))
 '(rst-level-1-face ((t (:foreground "#54ff9f"))))
 '(rst-level-2-face ((t (:foreground "#43cd80"))))
 '(rst-level-3-face ((t (:foreground "#2e8b57"))))
 '(rst-level-4-face ((t (:foreground "#6e8b3d"))))
 '(setnu-line-number ((t (:inherit (zenburn-lowlight-2)))))
 '(show-paren-match ((t (:underline nil :weight bold :background "#5f5f5f" :foreground "#dfaf8f"))))
 '(show-paren-mismatch ((t (:weight bold :inherit (font-lock-warning-face)))))
 '(speedbar-button-face ((t (:inherit (zenburn-primary-1)))))
 '(speedbar-directory-face ((t (:inherit (zenburn-primary-5)))))
 '(speedbar-file-face ((t (:inherit (zenburn-primary-2)))))
 '(speedbar-highlight-face ((t (:underline (:color foreground-color :style line)))))
 '(speedbar-tag-face ((t (:inherit (font-lock-function-name)))))
 '(strokes-char-face ((t (:inherit (font-lock-keyword-face)))))
 '(todoo-item-assigned-header-face ((t (:inherit (zenburn-primary-2)))))
 '(todoo-item-header-face ((t (:inherit (zenburn-primary-1)))))
 '(todoo-sub-item-header-face ((t (:foreground "#f0dfaf"))))
 '(tuareg-font-lock-governing-face ((t (:inherit (zenburn-primary-2)))))
 '(tuareg-font-lock-interactive-error-face ((t (:inherit (font-lock-warning-face)))))
 '(tuareg-font-lock-interactive-output-face ((t (:inherit (zenburn-primary-3)))))
 '(tuareg-font-lock-operator-face ((t (:inherit (font-lock-operator)))))
 '(twittering-uri-face ((t (:underline (:color foreground-color :style line) :inherit (zenburn-blue)))))
 '(twittering-username-face ((t (:inherit (zenburn-red-2)))))
 '(w3m-anchor-face ((t (:inherit (zenburn-primary-1)))))
 '(w3m-arrived-anchor-face ((t (:inherit (zenburn-primary-2)))))
 '(w3m-form-button-face ((t (:inherit (widget-button)))))
 '(w3m-form-button-mouse-face ((t (:inherit (widget-button-pressed)))))
 '(w3m-form-button-pressed-face ((t (:inherit (widget-button-pressed)))))
 '(w3m-form-face ((t (:inherit (widget-field)))))
 '(w3m-image-face ((t (:inherit (zenburn-primary-3)))))
 '(w3m-tab-background-face ((t (:inherit (zenburn-highlight-subtle)))))
 '(w3m-tab-selected-face ((t (:box (:line-width 1 :color nil :style pressed-button)))))
 '(w3m-tab-selected-retrieving-face ((t (widget-inactive nil :inherit (w3m-tab-selected)))))
 '(w3m-tab-unselected-face ((t (:box (:line-width 1 :color nil :style released-button)))))
 '(w3m-tab-unselected-retrieving-face ((t (widget-inactive nil :inherit (w3m-tab-unselected)))))
 '(wg-brace-face ((t (:inherit (wg-mode-line-face)))))
 '(wg-command-face ((t (:inherit (wg-mode-line-face)))))
 '(wg-current-workgroup-face ((t (:inherit (wg-mode-line-face) :foreground "#8c5353"))))
 '(wg-divider-face ((t (:inherit (wg-mode-line-face) :foreground "#400000"))))
 '(wg-filename-face ((t (:inherit (wg-mode-line-face)))))
 '(wg-frame-face ((t (:inherit (wg-mode-line-face)))))
 '(wg-message-face ((t (:inherit (wg-mode-line-face)))))
 '(wg-mode-line-face ((t (:weight bold :foreground "#400000"))))
 '(wg-other-workgroup-face ((t (:inherit (wg-mode-line-face)))))
 '(wg-previous-workgroup-face ((t (:inherit (wg-mode-line-face)))))
 '(wgrep-delete-face ((t (:strike-through "#Ff7f24"))))
 '(wgrep-face ((t (:foreground "Black" :background "#698b69"))))
 '(which-func ((t (:inherit (mode-line)))))
 '(wl-highlight-folder-few-face ((t (:inherit (zenburn-red-2)))))
 '(wl-highlight-folder-many-face ((t (:inherit (zenburn-red-1)))))
 '(wl-highlight-folder-path-face ((t (:inherit (zenburn-orange)))))
 '(wl-highlight-folder-unknown-face ((t (:inherit (zenburn-blue)))))
 '(wl-highlight-folder-unread-face ((t (:inherit (zenburn-blue)))))
 '(wl-highlight-folder-zero-face ((t (:inherit (zenburn-fg)))))
 '(wl-highlight-message-citation-header ((t (:inherit (zenburn-red-1)))))
 '(wl-highlight-message-cited-text-1 ((t (:inherit (zenburn-red)))))
 '(wl-highlight-message-cited-text-2 ((t (:inherit (zenburn-green+2)))))
 '(wl-highlight-message-cited-text-3 ((t (:inherit (zenburn-blue)))))
 '(wl-highlight-message-cited-text-4 ((t (:inherit (zenburn-blue+)))))
 '(wl-highlight-message-header-contents ((t (:inherit (zenburn-green+1)))))
 '(wl-highlight-message-header-contents-face ((t (:inherit (zenburn-green)))))
 '(wl-highlight-message-headers-face ((t (:inherit (zenburn-red+1)))))
 '(wl-highlight-message-important-header-contents ((t (:inherit (zenburn-green+2)))))
 '(wl-highlight-message-important-header-contents2 ((t (:inherit (zenburn-green+2)))))
 '(wl-highlight-message-signature ((t (:inherit (zenburn-green)))))
 '(wl-highlight-message-unimportant-header-contents ((t (:inherit (zenburn-lowlight-2)))))
 '(wl-highlight-summary-answered-face ((t (:inherit (zenburn-blue)))))
 '(wl-highlight-summary-displaying-face ((t (:weight bold :underline (:color foreground-color :style line)))))
 '(wl-highlight-summary-disposed-face ((t (:slant italic :inherit (zenburn-lowlight-2)))))
 '(wl-highlight-summary-new-face ((t (:inherit (zenburn-blue)))))
 '(wl-highlight-summary-normal-face ((t (:inherit (zenburn-fg)))))
 '(wl-highlight-summary-refiled-face ((t (:inherit (zenburn-lowlight-2)))))
 '(wl-highlight-summary-thread-top-face ((t (:foreground "#f0dfaf"))))
 '(wl-highlight-thread-indent-face ((t (:foreground "#dc8cc3")))))

(provide-theme 'my-zenburn)
